### ISSUE TITLE
Support formatting of date components as words

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#1009]
Golang supports formatting date components as words, e.g. `Jan` or `Monday`.

We could follow Java syntax in mapping these to the golang formatting strings, e.g.

`MMM` => `Jan`  
`MMMM` => `January`  

Challenge is localization

**Comment by nicpottier** [comment]
Ya, localization has always been my resistance here, but agree this is probably too high of utility to pass up anymore. Wonder if there's a file somewhere that has at least the most common languages covered we could leverage?

**Comment by rowanseymour** [comment]
There's https://github.com/klauspost/lctime tho it's archived - maybe a starting point

**Comment by nicpottier** [comment]
Looks like the dates come from: https://lh.2xlibre.net/locales/

But ya, maybe worth forking and/or just including their locale pieces?

**Comment by rowanseymour** [comment]
Yeah.. and golang 1.16 just made it easier to embed files!
