### ISSUE TITLE
Similar implementation of SUM

### ISSUE THREAD

**Issue by rafaelbreno** [nyaruka/goflow#1015]
I saw that `@SUM` what discontinued, and that it can be done with `@(val1 + val2 + val3...)`, but if there's an array `@array(1, 2, 3, 4, 5, 6)` how could I sum all values? 

There's some kind of way to implement a `@foreach` ? Or would need to create a loop in the FlowEditor using the `@count()` to see how many item that I have in that array, an then loop through `n` times, adding up to an specific flow result.

**Comment by rowanseymour** [comment]
Been pondering on this as it's not the first time someone has asked about summing array elements..

1. Add a function like `sum(array)`. There aren't many ways users commonly want to reduce an array so `sum(array)` and `join(array, sep)` (already exists) probably cover most of them.
2. Add a `reduce` function and a `sum(args...)` function and let them write it functionally like `@(reduce(arr, sum))`
3. [Add lambdas](https://github.com/nyaruka/goflow/issues/768)! and let users write it something like `@(reduce(arr, x,y => x + y))`

I think I'd lean toward 1 even if we later add more FP support. Also `sum` would match how it's done in Python..
