### ISSUE TITLE
@count() always return 11

### ISSUE THREAD

**Issue by rafaelbreno** [nyaruka/goflow#1016]
I created a Flow on TextIt with the following structure:

![array_long](https://user-images.githubusercontent.com/32229014/120371975-fb5a4680-c2ec-11eb-8393-eeabef07a93d.png)
![array_one](https://user-images.githubusercontent.com/32229014/120371989-feedcd80-c2ec-11eb-9a7a-52fbcc85a7e8.png)

For both of them `@count()` returns 11.

**Comment by rowanseymour** [comment]
This isn't a problem with `count` - it's a problem that results are just strings - i.e. they aren't JSON like objects or arrays. I think it's actually telling you that `results.arr` is an object with 11 properties..

`@(count(parse_json(results.arr)))` would work I think..

**Comment by rafaelbreno** [comment]
That makes sense, thanks
