### ISSUE TITLE
Don't include router fields in PO extraction for subflow, webhook nodes etc

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#1076]
Not quite sure yet what the logic here should be - it kinda needs to match what the editor considers localizable but the engine doesn't know about node types in the UI. Maybe for any node that has both an action and a router, the router isn't localizable?

**Comment by rowanseymour** [comment]
@ericnewcomer maybe it's ok if PO translation doesn't cover everything translatable in the UI. We could say that it includes everything the engine considers localizable on actions.. and I think that would be a subset of everything the editor considers translatable. That way people can use it for send message text... but router args, which usually require more context, should be translated in the editor.

**Comment by ericnewcomer** [comment]
I think it's an anti-pattern to translate rules outside the context of a flow, so I'm all for removing them here. Slightly less convinced about categories though.

**Comment by rowanseymour** [comment]
We got rid of option to include router arguments (change is actually in mailroom to exclude properties called `arguments`)
