### ISSUE TITLE
Remove from all groups

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/goflow#140]
Remove from group action needs to support _remove from all groups_ flag and migrate appropriately

**Comment by rowanseymour** [comment]
Looking at https://github.com/rapidpro/rapidpro/pull/188 and it seems we implemented this by reusing the same action but saving all groups on it - so no changes needed in goflow... but does new editor do this differently?

**Comment by ericnewcomer** [comment]
Currently it’s in the same action in the new editor as well.

**Comment by rowanseymour** [comment]
This is fixed with addition of "all_groups" flag
