### ISSUE TITLE
Add validation for HTTP verbs

### ISSUE THREAD

**Issue by ycleptkellan** [nyaruka/goflow#143]
Seems like an MVP implementation of the webhook router should include this verb as updating an existing resource appears to be a fairly common use case for the 'Call Webhook' step.

**Comment by nicpottier** [comment]
Current implementation just uses the method passed in:
  https://github.com/nyaruka/goflow/blob/master/flows/actions/call_webhook.go

So this will actually work as is. May make sense to add some validation for real HTTP verbs into this action though.

**Comment by ycleptkellan** [comment]
Ah OK thanks. Makes sense to me, updated issue

**Comment by rowanseymour** [comment]
Added in #164
