### ISSUE TITLE
Clean up logging

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#161]
1. Don't need `request_started` and `request_complete`
2. Don't need request id
3. Don't need `user_agent`
4. Don't need `remote_addr`
5. Don't need `http_scheme`

**Comment by rowanseymour** [comment]
Doesn't look like there's currently a way to customize any of that (e.g. https://github.com/pressly/lg/pull/2/).... ezlog @nicpottier ?

**Comment by nicpottier** [comment]
I did it for courier, you just write your own request middleware.

**Comment by rowanseymour** [comment]
Fixed in #186
