### ISSUE TITLE
Action name cleanup

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#172]
We could be a bit more consistent about things like `set` vs `save` vs `update`.. etc

|Current name                       | Event(s) generated              |
|---------------------------|----------------------------|
| add_urn | contact_urn_added |
| add_to_group | contact_groups_added |
| remove_from_group | contact_groups_removed |
| set_preferred_channel | contact_channel_changed |
| update_contact | contact_property_changed |
| save_contact_field | contact_field_changed |
| save_flow_result | run_result_changed |
| call_webook | webhook_called |
| add_label | input_labels_added |
| reply | msg_created |
| send_email | email_created / email_sent |
| send_msg | broadcast_created |
| start_flow | flow_triggered |
| start_session | session_triggered |

Possible actions that we might add in future:
- Play / Say for IVR
- Airtime sending
- USSD ?

**Comment by ericnewcomer** [comment]
Kinda weird having update and save. Difference is I guess save can be creating things or saving? Feels some common language might be better though.

**Comment by rowanseymour** [comment]
How about:

|Old name          |New name    | Event(s) generated              |
|------------|-----------|-------|
| add_urn | add_contact_urn | contact_urn_added |
| add_to_group | add_contact_groups | contact_groups_added |
| remove_from_group | remove_contact_groups | contact_groups_removed |
| set_preferred_channel | set_contact_channel | contact_channel_changed |
| update_contact | set_contact_property | contact_property_changed |
| save_contact_field | set_contact_field | contact_field_changed |
| save_flow_result | set_run_result | run_result_changed |
| call_webook | call_webook | webhook_called |
| add_label | add_input_labels | input_labels_added |
| reply | send_msg | msg_created |
| send_email | send_email | email_created / email_sent |
| send_msg | send_broadcast | broadcast_created |
| start_flow | start_flow | flow_triggered |
| start_session | start_session | session_triggered |

**Comment by nicpottier** [comment]
yes yes yes!

**Comment by rowanseymour** [comment]
Team editor? @ericnewcomer @ycleptkellan

**Comment by ycleptkellan** [comment]
looks good to me 👍

**Comment by rowanseymour** [comment]
Done in #178
