### ISSUE TITLE
Figure out strategy for group msgs

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#18]
Likely solution is something where we return a context of the flow at that place and it is up to container to deal with substituting contact vars

**Comment by rowanseymour** [comment]
We just chatted about this and current preferred solution is to allow messages to be sent to other contacts, but `@contact` is still the flow contact and we'd get rid of `@step.contact`. This would make it behave similarly to the send_email.

**Comment by nicpottier** [comment]
No group messages, only flow starts.
