### ISSUE TITLE
Make lists accessible in expressions

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#182]
Currently you can access individual items in lists, but we need a consistent way to handle an expression evaluating to a list (e.g. contact.groups, contact.urns).

Could stringify as CSV, or return a JSON array 

See https://github.com/nyaruka/goflow/blob/master/flows/engine/session_test.go#L32

**Comment by nicpottier** [comment]
Seems like maybe we should support passing back a slice of resolvers? That would then let us implement a toString() and toJSON() for that type?

**Comment by rowanseymour** [comment]
Ok thinking this through with some examples. I think we want:

`@contact.urns` → `tel:+123456, twitter:bobby` (i.e. `String()` of each URN)
`@contact.groups` → `Males, Reporters, Staff` (i.e. `String()` of each group)

So `conversions.ToString()` on a slice of `fmt.Stringer`s is concatenating all the `String()` return values.

For maps we can make `conversions.ToString()` smart about a value of type `map[string]fmt.Stringer` so that...

`@run.results.foo` → `bar`
`@run.results.score` → `123`
`@run.results` → `foo: bar, score: 123` (i.e. `String()` of each map item)

Then for JSON output we can introduce add an interface like...

```go
type JSONable interface {
  JSON() map[string]interface{}
}
```

and an excellent function like `JSON()` which takes one of:
* `JSONable`
* `[]JSONable`
* `map[string]JSONable`
* all the above but for `fmt.Stringer`

`@(JSON(contact.urns))` → `["tel:+123456", "twitter:bobby"]`
`@(JSON(run.results))` → `{"foo": {"value": "bar", "category": "Bar"}...`

How does that sound? One real usecase we have already identified - we need `@(JSON(run.results))` to replicate our legacy webhook payload

**Comment by nicpottier** [comment]
That JSON returns a map/string interface feels wrong to me. An obvious example would be that we may want the JSON value for a datetime to be different than its string value and that interface definition doesn't allow us to specify our own JSON to do that. Maybe it just needs to return interface{} or maybe even just []byte?

One pending item that I think is critical is some way of validating that everything in the context works from a Stringer point of view and from a JSON resolving point of view.

I think we have two avenues of accomplishing that. 

1. We do it compile time and force everything to be a Stringer/JSONer and force all our things to return those appropriate types. (perhaps it is one interface with both methods)

2. We have a unit test that builds a mega context that holds all the things it can hold, then serialize it step by step as a string and as json.

Option 2 feels like it might lead to more natural interfaces (IE, we don't need to wrap native types, instead our conversions can take care of those), though it does feel more error prone.

**Comment by rowanseymour** [comment]
Makes sense that the return type of `JSON()` is something more generic than a map. If it's `interface{}` then most objects can return a map or primitive and we can do the marshalling to bytes in one place for them instead of repeating that everywhere. Maybe we make an exception for JSONFragment as it is just bytes.

Option 2 sounds feasible - 1 ) build a regular context in a test, 2) update `ToString` blow up if it can't convert something 3) try to JSONify the whole shebang.

All this talk of things in the context reminds me that I still don't fully get what `Default()` does...

**Comment by nicpottier** [comment]
Ya, need to revisit Default to see if any of them ever return anything that is different than themselves.

**Comment by rowanseymour** [comment]
Throwing this out there as another approach worth considering - the _everything is JSON_ approach. In this approach, everything that can't be rendered as a primitive value, renders itself as JSON. 

Nice thing about this is that all complex values have a consistent format. We have a few things in the context which can only be JSON (`run.webhook.json`, `trigger.params`) so it becomes a little confusing when other parts of the context (e.g. `run.results`) require explicit JSON rendering with a function call.

`contact.urns` → `["tel:+123456", "twitter:bobby"]`
`contact.urns.0` → `tel:+123456`
`run.results` → `{"color": {"value": "red", "category": "Red", ... }}`

The downside of this approach (which also exists in the prior approach) is that a more specific context path doesn't always return the same thing is what you'd see for that item in a broader context path, i.e. 
 `run.results.color` → `red` doesn't give the whole dict `{...}` like you see for `color` when you use `run.results`.

**Comment by nicpottier** [comment]
I think its important to differentiate the two use cases here because I think they are different.

1. Referring to something in a context which say you are passing to a function
2. Taking a result from a function or stem/leaf in the context and rendering it as text in a template

I like the idea of 2) being basically "it's JSON" and replacing our `String()` "casting" to something more like JSON casting (where a string primitive is indeed JSON). That seems like a useful simplification. But I also think that it is important that 1) remains as full GoLang objects from a flexibility point of view. You only enter JSON land once you are resolving to a "string"

**Comment by rowanseymour** [comment]
Yeah agree - if you pass a URNList to a function it's still a URNList. Maybe something "JSONishy" is one of the primitive types that `conversions.ToString` knows how to stringify when required.

I'm gonna try ripping out `Default` and see if that makes the solution more obvious...

**Comment by rowanseymour** [comment]
After discussion we've opted to keep string and JSON representations distinct, see https://nyaruka.github.io/goflow/

**Comment by rowanseymour** [comment]
This is done - things like `contact.urns` are array-like and functions like `split` return arrays.
