### ISSUE TITLE
Revisit constants used in date formatting

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#192]
We kind of use our own constants for date formatting.. would like to double check these both for consistency and see if we should be using the standards from another system there instead.

**Comment by nicpottier** [comment]
Current formatting constants are:

```
// * `d`     - day of month, 1-31
// * `dd`    - day of month, zero padded 0-31
// * `fff`   - thousandths of a second
// * `h`     - hour of the day 1-12
// * `hh`    - hour of the day 01-12
// * `H`     - hour of the day 1-23
// * `HH`    - hour of the day 01-23
// * `K`     - hour and minute offset from UTC, or Z for UTC
// * `m`     - minute 0-59
// * `mm`    - minute 00-59
// * `M`     - month 1-12
// * `MM`    - month 01-12
// * `s`     - second 0-59
// * `ss`    - second 00-59
// * `tt`    - am or pm
// * `TT`    - AM or PM
// * `yy`    - last two digits of year 0-99
// * `yyyy`  - four digits of your 0000-9999
// * `zzz`   - hour and minute offset from UTC
```

Things I like / don't like:
 * it is fairly obvious what most things map to just from the first letter, the only exception is minute and month, and there the bigger thing is capitals, so that seems ok
* `TT` and `tt` are weird, though maybe ok?
* `H` and `HH` are kinda weird too, ideally I'd like all capital letters to be things that are a day or greater, and lowercase things to be things a day or smaller. So that would mean changing `yy` and `yyyy` to `YY` and `YYYY` and `d` and `dd` to `D` and `DD`, but not sure what we do with `H` and `HH`. New letter for 24 hour time?
* `zzz` should probably be `ZZZ` by that logic? (to be consistent with `K` at least)

**Comment by nicpottier** [comment]
Adding `W` and `WW` for week of the year is probably not a bad idea.

**Comment by nicpottier** [comment]
Python formatting constants:
  https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior

C formatting constants:
  https://www.gnu.org/software/libc/manual/html_node/Formatting-Calendar-Time.html

Java formatting constants:
  https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html

**Comment by nicpottier** [comment]
Golang formatting:  
  https://golang.org/pkg/time/#pkg-constants

**Comment by nicpottier** [comment]
Popular JS library: 
  http://blog.stevenlevithan.com/archives/date-time-format

**Comment by nicpottier** [comment]
So I think I'll make these changes:
 * Switch `TT` to `aa` and `AA`
 * Switch `d` and `dd` to `D` and `DD
 * Switch `yy` and `yyyy` to `YY` and `YYYY`
 * Switch `zzz` to `ZZZ`
 * Switch `K to `Z`
 * Switch `H` and `HH` to `t` and `tt` (for Twenty four)

That keeps us consistent that capitals are always things "bigger" than a day, everything else is lower case. Makes `m` and `M` easier to remember off the top of your head.

Thoughts @rowanseymour ?

**Comment by rowanseymour** [comment]
Only bit I don't love is `tt` for 24 hour time, but that might be because I'm so used to `HH` and I do think lowercase for smaller timey components is a useful distinction...
