### ISSUE TITLE
Function like array(xvalue...) xarray ?

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#220]
Hard to think of a real world need but it would be certainly useful in tests so one doesn't have to rely on `split("a, b, c")` to generate an array.

One possible use would be a kind of switch statement equivalent, e.g.

```
@(array("yes", "no", "maybe")[run.results.foo])
```

**Comment by nicpottier** [comment]
Ya, we either need this or to work it into the excellent parser. ie:

`@(["yes", "no", "maybe"])`

It does sound easier to make a new function though maybe its worth the effort to make the parser handle this? Do we want constructors like this to start with `to_`? strikes me we probably want a `to_string` as well as the existing `to_json`?

**Comment by rowanseymour** [comment]
Yeah the ease of creating a function to do this is tempting. I guess there might also be something to be said for the simplicity of `[1]` always meaning an index operation and not a literal with a single decimal? No strong feelings either way but think I lean toward a function.

Are `to_string` / `to_json` constructors or conversions? I would expect `to_` methods to take an existing type and use the same conversion logic we do implicitly in other places. I think `array` would be more like `date_from_parts` etc.

**Comment by nicpottier** [comment]
Ya I think all that makes sense.

**Comment by rowanseymour** [comment]
Added in #223
