### ISSUE TITLE
Centralised checking and conversion of function parameters

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#230]
The work of making actual parameters align with the declared parameters could be done in one place for all functions. Instead of declaring a function like:

```
Word(env utils.Environment, args ...XValue) XValue
```

And then having `Word` figure out if it has the correct parameters, it becomes:

```
Word(env utils.Environment, XString, XNumber) XString
```

Then it's up to `VisitFunctionCall `generate the correct parameters using reflection, which means:
  * Consistent error messages when parameters are wrong
  * Consistent rules of conversion (see #229)

**Comment by nicpottier** [comment]
Ya, this does smell a bit currently. I think the Go-ish way to do this would be to have anonymous function wrappers, not reflection.. so something like:

```
func Capitalize(env utils.Environment, XString) XString {
}
```

And in your mapping something like:

```
"capitalize": XStringReturn(XStringFunction(Capitalize)),
```

**Comment by nicpottier** [comment]
Actually I guess you can't do both the return and function parsing separately.. though I don't think casting the return value buys you anything, so just having wrappers to do the parameter casting probably makes the most sense.

**Comment by rowanseymour** [comment]
#228 adds several wrappers like above. Turns out you can never enforce return type because it can always something OR an XError. Closing this for now but might still be room for improvement here was the wrapper approach requires a wrapper function for every possible combination of function args.
