### ISSUE TITLE
word, word_count and word_slice can all take a boolean final arg in legacy expressions

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#237]
It defaults to false and indicates that tokenizing should only happen by whitespace. Need to be able to migrate this or verify it's not being used.

**Comment by rowanseymour** [comment]
It's definitely being used because it was the solution to someone's ticket recently

**Comment by nicpottier** [comment]
This was Lisa's question right? Was that the right solution though in the new world?

**Comment by rowanseymour** [comment]
She was having a problem with "O'Grady" becoming two words. Currently all tokenization in new world goes through `utils.TokenizeString` which treats that as two words... so I think we have to add the equivalent functionality in the new world

**Comment by nicpottier** [comment]
I REALLY don't like having a boolean flag. What about passing in the characters you want to split on instead?

**Comment by rowanseymour** [comment]
Yeah me neither (which is why I was really hoping to avoid adding it because you can't tell by looking at what it does). I like the idea of migrating `@(WORD(foo, TRUE))` to `@(word(foo, " "))`
