### ISSUE TITLE
Legacy trigger-flow action copies @extra from current run to new run

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#269]
We don't even make webhooks of parent and child runs accessible in the context

**Comment by rowanseymour** [comment]
After further digging: in RP, webhook results and regex matches are written into `FlowRun.fields` which is exposed as `@extra` in expressions. When `TriggerFlowAction` starts a child run, it copies extra from the current run. 

We could emulate this behavior by adding a `apply_webhook_called` method to update `FlowRun.fields`, and then passing that as `trigger.params` when creating the child session.

**Comment by rowanseymour** [comment]
We could look for expressions that access `@extra` in flows that don't have actions that modify `@extra` - but we'd have to exclude cases where API users provide extra. But not seeing anyway to reliably determine that an expression is accessing something in `@extra` that came from the parent.

**Comment by nicpottier** [comment]
Ya, I like the idea of looking at whether `@extra` is actually used and only populating it in those cases.

**Comment by rowanseymour** [comment]
Run results on a `flow_action` trigger (equivalent of legacy `TriggerFlowAction`) now contribute to `@legacy_extra`. Not perfect because that parent run might also have trigger params or another parent with results... but possibly close enough (see ae8bad7e9c0f507653fbb641804be7b91576c929)
