### ISSUE TITLE
Legacy webhook ruleset create different run results

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#270]
Legacy webhook rulesets use a `WebhookStatusTest` which saves the webhook response body as the match, and leaves input empty, e.g.

```json
{
  "category": "Success",
  "node_uuid": "9b5147c2-fa6c-4ef2-8684-4bf20c2c6fcb",
  "name": "Response 1",
  "value": "{ \"text\": \"Get\", \"blank\": \"\" }",
  "created_on": "2018-04-23T22:37:39.071144546Z",
  "input": ""
}
```

New webhook rulesets us a `is_text_eq` test on the webhook status, so their match and input is the status string, e.g.

```json
{
  "category": "Success",
  "node_uuid": "9b5147c2-fa6c-4ef2-8684-4bf20c2c6fcb",
  "name": "Response 1",
  "value": "success",
  "created_on": "2018-04-23T22:37:39.070738018Z",
  "input": "success"
}
```

Two possible solutions:

 1. Add a webhook status test that replicates behavior of `WebhookStatusTest`
 2. Add an additional `set_run_result` action to explicitly save a result like what `WebhookStatusTest` would produce.

**Comment by nicpottier** [comment]
From an export and tracking point of view the old behavior sounds nicer to me, and since results are just JSON blobs maybe that is just fine?

**Comment by rowanseymour** [comment]
Yeah that's my inclination too. Also have a preference at this point toward goflow 1.0 not trying too hard to do things differently.

**Comment by rowanseymour** [comment]
If I recall correctly, part of the drive toward more generic tests like `is_text_eq` was that router tests used to live in the `excellent` package and so it was tricky to have them know about things like webhooks which live in the `flows` package - but we recently moved router tests into `flows` so that's no longer a problem.
