### ISSUE TITLE
Add a way of getting JSON of a context branch

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#30]
IE, do something like `@(TO_JSON(run.results))` and get something like: 

```
{
   "foo_bar": {

   }, etc..

}
```

**Comment by rowanseymour** [comment]
#228 adds a required method `ToJSON() XString` to all values allowed in the context - tho for now they mostly return "TODO" and still need to implemented

**Comment by rowanseymour** [comment]
Added in #236
