### ISSUE TITLE
JSON data is normalized in legacy engine 

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#367]
When a webhook returns JSON or a flow is started via the API with extra, the saved extra is normalized, e.g. `{"Foo Bar": "Hello"}` -> `{"Foo_Bar": "Hello"}`. When it's referenced in an expression, the key lookups are case-insensitive, e.g. `@extra.foo_bar` returns `"Hello"`. 

In contrast, goflow just stores the raw JSON and uses the `jsonparser` library to resolve keys as needed. To look up the above JSON you would write something like `@(run.webhook.json["Foo Bar"])`.

So we have two options:
  - Switch to normalizing all JSON like the old engine. It could still be lazy - when you try to resolve `run.webhook.json` we parse the webhook body into something that resolves it like the old world. 
  - Add a function to maintain normalized lookups for `@extra` in migrated flows, e.g. `@(legacy_extra(run.webhook.json).foo_bar)`

Is it better that `run.webhook.json` behaves like the rest of the context, or behaves like actual JSON?

One complication with second approach is that `@extra` is already migrated to a fairly complicated expression, since what was `@extra` is now in one of two different places, e.g. 

`@(if(is_error(run.webhook.json.foo_bar), trigger.params.foo_bar, run.webhook.json.foo_bar))`. 

But maybe this allows us to simplify that for migrated flows, and lean on the custom function more, e.g. 

`@(legacy_extra(trigger.params, run.webhook.json).foo_bar)`

or even...

`@(legacy_extra().foo_bar)`

**Comment by nicpottier** [comment]
I don't think we can do `@(legacy_extra())` can we? excellent doesn't have globals apart from env does it? I guess we could stuff in a `@(legacy_extra.foo_bar)` into the context though and maybe that's the simplest? Who has `legacy_extra` populated though? Only migrated flows?

**Comment by rowanseymour** [comment]
Well it feels cheaky but we can because we have the environment and that's an instance of `RunEnvironment` which has the run. We do this for tests like `has_state` to get at the location data which is associated with the session.

**Comment by nicpottier** [comment]
Ya, that feels like a much worse bastardization than location data which feels more 'environmenty' for sure. I would rather stuff the context with stuff.

**Comment by rowanseymour** [comment]
Addressed in #368
