### ISSUE TITLE
Formatting for @results

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#401]
In old engine, `@flow` renders a list like 

```
key1: value1
key2: value2
...
```

which you sometimes see in things like `EmailAction`. In new world `@results` renders as raw JSON. Maybe we can add function like `@(report(results))`...

**Comment by rowanseymour** [comment]
So think we have to add this since we have at least one user wondering why `@flow` in his SendEmail is now becoming raw JSON. I think the solution is a function that can take something map like, i.e.

- `@contact.fields`
- `@results`, `@parent.results` or `@child.results`
- An `XMap`
- An `XJSONObject` fragment 

Namewise probably should be something like `format_results` or `format_map` to match the other `format_` functions

**Comment by nicpottier** [comment]
Ya, I like this. `_map` feels too techy and `_report` seems too vague.

What about just a `format()` that you pass anything to and we do our best?

**Comment by rowanseymour** [comment]
By anything you mean anything or anything map like? I just mean does `format()` work for numbers and dates etc ?

**Comment by ericnewcomer** [comment]
I think it should be valid for anything. Worst case it’s a noop. Users don’t necessarily know what the type is. It’s basically pretty print for whatever.

**Comment by nicpottier** [comment]
Ya, I think if you pass in something that we know the type of, then we do our best.

IE `format(DATE("arst"))` is roughly same as `format_date("arst")`

**Comment by nicpottier** [comment]
same with URN etc..

**Comment by rowanseymour** [comment]
Yeah like that. Having a think about how to make this work with any complex object. Right now all XValues have a `ToXJSON`. That's typically implemented by returning a map of `string` -> `XValue` and then recursively JSONifying everything in that map - but if you took each value in that map and stringified it instead, you'd get a nice string -> string map.

```
@(format(contact)) =>

name: Bob
language: eng
...

```

**Comment by nicpottier** [comment]
Yep yep.. though how is nesting done? tab / space to show that?

**Comment by rowanseymour** [comment]
Well I was thinking no nesting - i.e. every value is just the TEXT version of that value, i.e. so you get

```
gender: male
age: 24 
```

and not

```
gender:
  text: male
age:
  text: 24
  number: 24
```

**Comment by nicpottier** [comment]
What's the JSON version? Maybe they should have the same rough structure?
What happens with arbitrary JSON when you pass it to this?
What about lists? IE urns?

**Comment by rowanseymour** [comment]
Ok rewinding for a second... the immediate need is to emulate the legacy behavior of `@flow` which renders as a simple list of key value pairs. It would be interesting to have a YAML like version of `@(json(x))` but I don't think that's what users want to put in emails etc.

```
format_???(results) =>
Foo: abc
Bar: 123
```

My initial thought was that it should be usable on anything map like, `@results`, `@contact.fields` etc tho the challenge there is that the legacy rendering of `@flow` uses result names as keys instead of the actual result keys... so hard to match that in a generic way that just treats all those things as maps.

It's perhaps a secondary question then as to whether we want to add a generic `format()` function which inspects type and defers to the existing type specific routines.

```
format(123.000) == format_number(123.000) == 123
format(date(d)) == format_date(d) == 22-02-2019
format(contact.urns[0]) == format_urn(contact.urns[0]) == (360) 123-4567
format(array(1, 2, 3)) == [1, 2, 3]
format(results) == format_???(results) == ?
```

**Comment by nicpottier** [comment]
But maybe these don't have to be different.

Can we add a new `XFormatable` interface that things can choose to implement if they want to do something special? That would be used by results to do just the single depth version. But XDate, XTime, XJSON etc, may have their own versions?

Would rather have one way to do this than two. Agree that results should be the simplified form but maybe that is solvable with an interface that allows us to be fancier in some cases.

**Comment by nicpottier** [comment]
Alternatively, what is the string representation of `@results`? Should it just be that and you have to use `JSON(results)` to get the json version?

**Comment by rowanseymour** [comment]
Sure sure I just don't want to lose track of the specific user need that brought us to this discussion.

Right now...

- `@contact` stringifies as name
- `@contact.fields` stringifies as JSON... basically cuz we have no idea how else to format it
- `@contact.fields.age` stringifies as it's typed value, e.g. `37`
- `@results` stringifies as JSON
- `@results.age` stringifies as it's `.value`
- a date, datetime or time stringifies as ISO

and then additionally you have the option for some types to use a `format_??` function to humanize/customize the stringification. For example for a date value...

```
@(date(mydate)) => 2019-02-22 // i.e. stringification via XDate.ToXText
@(format_date(mydate)) => 22-02-2019
@(json(mydate)) => "2019-02-22" // via XDate.ToXJSON
```

So then maybe then we just want to change the stringification of complex things like `@contact.fields` and `@results` so that they produce pretty lists without any need to call `format`

( But I also think a unified `format` function would be nice )

**Comment by nicpottier** [comment]
Ok ya. Agree that I think we should just change stringifies for `@results` and `@contact.fields` to basically `\n` joined key/value pairs. You can `JSON()` wrap them if you want json form.

Agree that high level format would be nice to have but can be a separate thing.

**Comment by rowanseymour** [comment]
And we're back full circle to planning to add a `format_results(..)` function

**Comment by rowanseymour** [comment]
Added in #635
