### ISSUE TITLE
WebhookStatus needs more granularity

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#416]
Currently we only have "success", "connection_error" and "response_error". We need something that represents `410` gone for resthooks. Or perhaps we include the raw status code in the webhook event as well to let us look at that.

**Comment by rowanseymour** [comment]
Yeah I'd lean toward it being the responsibility of the `CallResthookAction` to determine more clearly that the caller should remove that subscriber rather than the caller knowing to interpret a 410 correctly. New status of `subscriber_gone` that's only for resthooks ?

**Comment by rowanseymour** [comment]
Fixed in #418
