### ISSUE TITLE
Contact channel change action should generate URN changed events

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#427]
The `set_contact_channel` action modifies a contact's URN's changing their order and affinity. It currently generates a `contact_channel_changed` event which just lists the channel from the action but this doesn't describe well what happened.

Maybe we need to introduce a `contact_urns_changed` event which could also be used by the `add_contact_urn` action? Difficulty is that unlike groups, URN order is important.

**Comment by nicpottier** [comment]
Seems like `contact_urns_changed` which outputs the new ordered list in cases where things changed would make the most sense. Could then be used for the AddContactURN action as well. Bit of a pain for mailroom to then figure out smallest diff to apply that but not the end of the world. Only trick on engine level is that it is only output when it actually changes the contact's URNs. (IE, the action can be a noop)

**Comment by rowanseymour** [comment]
So despite what I might have said previously, `AddContactURN` adds a URN to the end of the list (in old engine too). I would imagine in the future we might want to allow adding to the beginning or end, but either way, it does seem like it returning the complete list is appropriate here.

**Comment by rowanseymour** [comment]
Fixed in #428
