### ISSUE TITLE
Handling of flows that change

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/goflow#43]
RP has a unit test that: 

* Starts the flow, stopping at a wait
* Modifies that wait into a passive split
* Sends a new message to resume _through_ that ruleset having the message picked up by the next wait

Seen here: `temba.flows.FlowsTest.test_rule_changes_under_us`

Running this sort of test in the new world results in `cannot resume flow at node [uuid] which no longer contains wait`.

Need to determine how want to mitigate this behavior going forward.

**Comment by rowanseymour** [comment]
@ericnewcomer I'm not seeing that test in any branch - is this a test you added somewhere? We do have some similar tests like `test_deleted_ruleset`

**Comment by ericnewcomer** [comment]
I removed this test and created a new test according to new behavior (we now end runs if they reside at nodes that get removed).
