### ISSUE TITLE
Date math inverted from old vs. new

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/goflow#442]
`@(DATEDIF(date.now, DATEVALUE("11-06-2018"), "D"))`

Executing this today in..
 * python: 8
 * goflow: -8

**Comment by nicpottier** [comment]
sure feels like -8 is right.

**Comment by nicpottier** [comment]
Although apparently my feeling is wrong:
  http://www-db.deis.unibo.it/courses/TW/DOCS/w3schools/sql/func_datediff.asp.html

**Comment by rowanseymour** [comment]
Fixed in #444
