### ISSUE TITLE
@contact.urn vs @contact.urns

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#447]
Currently `.urns` returns URN lists requiring users to use numeric indexes, or the `format_urn` function which can take a list and just use the first item. Confusingly `@contact.urn` isn't a URN object but a formatted string.

Proposal is that `.urn` provides access to single URNs, `.urns` provides access to URN lists. Most users are going to want to use `.urn`, but `.urns` is there to provide complete access to all the URNs when needed.

For the case of a contact with 4 URNs ("tel:+1234567890", "tel:+0987654321", twitter:bobby", "twitter:jimmy")

```
@contact.urn => "tel:+1234567890"
@contact.urn.tel => "tel:+1234567890"
@contact.urn.twitter => "twitter:bobby"
@contact.urn.scheme => "tel"
@contact.urn.path => "+1234567890"
@contact.urn.twitter.path => "bobby"

@contact.urns => ["tel:+1234567890", "tel:+0987654321", twitter:bobby", "twitter:jimmy"]
@contact.urns.tel => ["tel:+1234567890", "tel:+0987654321"]
@contact.urns.twitter => [twitter:bobby", "twitter:jimmy"]
@contact.urns.0 => "tel:+1234567890"
@(length(contact.urns)) => 4
@contact.urns.twitter.0 => "twitter:bobby"
@(length(contact.urns.twitter)) => 2
@contact.urns.0.scheme => "tel"
@contact.urns.0.path => "+1234567890"
```

* `.urns` would continue to appear in the JSON version of a contact (`@(json(contact)`) whereas `.urn` wouldn't as it's more just a set of shortcuts.
* `contact.urn` would be a real URN here - see #448 for how that becomes easier to format

**Comment by nicpottier** [comment]
Yep yep, I think this is the best balance of introducing `urn` gently to people who likely will never have a contact with more than one URN while still allowing the power of multiple urns and filtering by scheme for the more advanced use cases.

**Comment by rowanseymour** [comment]
Fixed in #449

**Comment by norkans7** [comment]
What about @contact.twitter ? does that stay as `@contact.twitter => "twitter:bobby"` ?

**Comment by nicpottier** [comment]
Do we even have `twitter` at all? Isn't it all `twitterid` now? (with display being the screen name)

**Comment by rowanseymour** [comment]
Yeah I think it's only for old Twitter URNs and imports
