### ISSUE TITLE
.display should resolve to the formatted version of all URNs

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#448]
Little confusing that users can access this in expressions but it's only used for some URN types, e.g. `twitterid:12415236236#bobby`. It should become the formatted version of any URN.

**Comment by nicpottier** [comment]
Yes, I think `display` to the user should always be just a user friendly version of the URN, regardless of scheme. For some schemes that is the screen name (which stick in `#display`) for tels it may be just the formatted number.

**Comment by rowanseymour** [comment]
Addressed in #450
