### ISSUE TITLE
Migrated webhook actions don't create results and therefore don't end up in @legacy_extra

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#451]
1. Could add a result_name in flow migration - would mean that new engine is creating a result that old engine wasn't. Not a huge deal but will make trialling of new engine fail.
2. Could migrate all webhook actions to be webhook rulesets

**Comment by nicpottier** [comment]
Weren't we also saying that we just didn't want webhook action alone in the new editor anyways? which would make 2) the right option here.

**Comment by nicpottier** [comment]
I think the only argument we had for the action was that if you had "fire and forget" style webhooks that you wanted to use, then forcing those to be splits would be slightly annoying. But we can always add that back later really.

**Comment by rowanseymour** [comment]
Addressing this in the old world with https://github.com/nyaruka/rapidpro/pull/2186 so that migrated flows will generate the same results/extra as their old world equivalents

**Comment by rowanseymour** [comment]
No more webhook actions
