### ISSUE TITLE
Add support for flow spec migrations

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#478]
Because 12.0 is unlikely to be the last flow version...

**Comment by rowanseymour** [comment]
The simplest version of this would be like how we do it in Python currently - the old flow is loaded into generic map of maps, and that's run through a series of transformation functions, e.g.

```go
func migrateTo_12_1(jsonFlow map[string]interface{}) (map[string]interface{}, error) {...}
```

However, working with `map[string]interface{}` in go isn't anywhere as easy as working with a dict in Python. Pondering on ways to use reflection to create a "snapshot of structs" of each flow version.

Would also be great if there was an easy way to visit all fields in a definition which are excellent templates. Maybe that could be achieved with struct tags and would save any migration which needs to rewrite expressions from having to know which fields can contain expressions.

**Comment by nicpottier** [comment]
Definitely agree that having an expression shortcut migration would be a neat thing.

Ya, go is pretty shit at this kind of random map manipulation. I think the other bit there is that many past migrations have actually required us to do db lookups which then gets us squarely out of the goflow world. (though maybe that's captured in assets actually)

Maybe `jsonparser` is good enough for a while with some utility methods to let us more easily define 'ActionMigrator' or `SwitchMigrator` or whatnot. (you specify a list of migrators and it takes care of walking the tree for you and calling your migrator)

To be clear I don't think it necessarily makes sense to start on this until we have a real migration, we just want to make sure we have everything we need in place such that if we DID need a migration we could do it without too much work. (so just the stub for 'ensure_current_version' equiv?)
