### ISSUE TITLE
Session can't be read if channel assets no longer exist

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#484]
`contact.urns` and `input.channel` have hard references to channels and err if channel doesn't exist.

**Comment by rowanseymour** [comment]
@nicpottier exploring that last option in #486. Idea is that all ReadX methods for things in the session would report back missing assets as asset references instead of blowing up. To be clear this not just a surveyor problem as any time we resume a session (which starts by reading it), we might run into missing assets.

**Comment by nicpottier** [comment]
I think that could work.. I guess then the flow would also still run but return errors when reaching said actions or are we still saying that at the time of execution all references need to be real? (I think I would prefer that honestly)

I'll still need to deal with missing items when dealing with events, as I can't throw out an event entirely if just one group is missing for example, but that should be fairly straightforward.

**Comment by rowanseymour** [comment]
So there's two types of thing in goflow:

1. actions, events etc which only have references to assets and in the case of actions, only resolve those assets at runtime. In the case of actions, the references might be expressions which can only be resolved at runtime. Internally they have `asset.???Reference` structs. Goflow doesn't do anything with events.. just outputs them and considers them immutable.
2. contacts, inputs, modifiers, etc which resolve assets a read time. Internally they have pointers to real assets. Partly cuz cuz when they are involved in an expression, it's too late to start looking up assets.

There's also a question of correctness here - it might seem weird that the session contact loses fields and groups at read time - but if a group no longer exists.. then the contact is no longer part of that group etc.

I don't think we should change actions or events - in the case of the latter - it's up to the caller to decide at _apply_ time to ignore a group or field that it can't find. And we also don't want events to be dropped from the session because assets become missing later on - they're a historical record of what happened.

But I think for the latter class of things - we need to be flexible about missing assets at read time. If you call `ReadModifier` and it's an `add_groups` modifier with a group that exists and one that no longer exists, you should get back a modifier that still works for the existing group.

**Comment by nicpottier** [comment]
Ya, just thinking aloud here as to how events are applied in mailroom and I think it works in that case too for two reasons:
  1. things like groups don't get hard deleted, just deactivated
  2. we aren't loading things like groups at that point, everything is already in our assets

So at worst in the case of a crazy race where at sprint start a group is active but at sprint commit time it has been deactivated we just create rows in our contact association table that are invalid. That's a bit of a shame but really in a concurrent system there's no real way around that except to introduce locking that would bring us to our knees. If it ever becomes a problem we can do some delayed clearing of associations in rapidpro when items are deactivated.

There may be other cases I'm not thinking about but I think everything kind of falls under that umbrella from mailroom's perspective during flow execution. (time will tell!)

Having modifiers return the "most complete possible" modifier seems just fine and at that point I think the rules are exactly the same as above. (all assets have been loaded, worst case we create associations for inactive things)

**Comment by rowanseymour** [comment]
Fixed in #486
