### ISSUE TITLE
Move logging up to mailroom

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#490]
Feels like the engine shouldn't be in the business of writing to a logrus logger but let the caller do that if they want instead. Only 2 lines in goflow left doing this anyway.

**Comment by nicpottier** [comment]
Yes, it shouldn't be going logging. In an ideal world maybe golang would have logging that let you turn on particular packages but I don't think that's needed. (maybe in golang that's done by fucking with a public logrus instance that goflow uses?)

But in either case I'd prefer that's turned off in goflow for the time being and we lean on errors and session contents for debugging.

**Comment by rowanseymour** [comment]
Fixed in f00ec0692428ce62f511ad166f8d729d60d8812a
