### ISSUE TITLE
Variance from old engine `input` in subflows

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#503]
Don't think we necessarily need to change this, but this is the type of thing we may need to document.

I believe the new engine only has `input` populated on the first run that gets the input, as it is part of the trigger, so it isn't passed down to subflows. This is different than how `input` was handled in the old engine and will definitely break some old flows.

**Comment by rowanseymour** [comment]
Actually inputs and waits are session-level in the new engine... so no passing down into subflows required.

**Comment by rowanseymour** [comment]
@nicpottier this ended up being a resthook issue, right?

**Comment by nicpottier** [comment]
Ya, I think this was the `null` vs nothing case, closing.
