### ISSUE TITLE
Better time manipulation

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#516]
Currently we don't have a good story for time manipulation which seems to be a fairly common use case. 

Currently something like `@(TODAY()+TIME(7, 30))`  becomes `@(datetime_add(today(), 27000, "s"))`

I.e. we don't have a time type so it becomes a date+seconds operation. The shortcomings of this are:

1. If the left-hand side might be a datetime that already has time information, there's no easy way to get just the date component of this.
2. The right-hand side has to be literals - we could fix this but the user would end up with a pretty complex looking expression.
3. No support for parsing a time value from text, like `TIMEVALUE` in legacy expressions.

Currently 3. means the expression `@(TODAY()+TIMEVALUE(flow.time))` becomes `@(datetime_add(today(), parse_datetime(results.time), "D"))` which is completely wrong.

I propose we make this usecase a lot simpler with the addition of 

- `time(num, num, num)` returns number of seconds-in-the-day as `XNumber`
- `parse_time(text)` returns number of seconds as `XNumber`
- `replace_time(datetime, num)` replaces all time data in the given datetime with the given time
- `format_time()` pretty prints a time value

But I could also be persuaded that time should be one of our primitive types... `XTime`

**Comment by nicpottier** [comment]
I don't think we can represent time as an offset because of daylight savings time. IE, 3pm is not the same number of seconds from midnight depending on the day of the year. So we have to have a representation that really is the hour / minute / second.

So I think time probably has to be something closer to "11:30" as a string, as passing around tuple would be annoying.

How far could we get with just a `replace_time(datetime, str)` method along with a `has_time` that tests and returns something that is like `11:30pm` or `23:30`? I guess with the addition of a `get_time(datetime)` that returned the same.

That would make setting the time to today be `replace_time(today, "7:30pm")` or `replace_time(today, "19:30")`

I guess the question is then do we want a special type for that? It may not need to be something we expose to the user per say but may make reasoning on our side easier. Though we will probably have flexible parsing of string like times either way.

**Comment by nicpottier** [comment]
So thinking about this a bit more I think we just adopt 8601 times, with an internal representation of the tersest `extended` format that includes both hour and minute.

IE. `22:30` or `22:30:30 or `22.30:30.500` but not just `22` and no internal representation of fractions for hour or minutes. (though we should support those and support commas for fractions)

We then add:
 * `PARSE_TIME(str) xtime, err` - parses things like `4:45pm` or `4pm` or just `7`
 * `TIME(datetime) xtime, err` - returns the tersest iso8601 time for a datetime
 * `HAS_TIME(str) xtime, err` - looks at all tokens in string looking for a time looking thing (could be simply a `5`, returns that time
 * `REPLACE_TIME(datetime, xtime)` - replaces the time for the datetime

I think that would give people the tools we need.

The other missing piece I think is around timezone support. I think we need:
 * `PARSE_TZ(str) xtz, err` which takes an "America/LosAngeles" string and returns a normalized timezone
 * `HAS_TZ(str) xtz, err` looks for first token that looks like a tz, returns it
 * `TZ(datetime) xtz` already exists, does what you expec
 * `SET_TZ(datetime, xtz)` sets the timezone on a datetime, this changes the epoch but keeps the time the same in that timezone
 * `IN_TZ(datetime,xtz)` converts the datetime to the passed in timezone. Epoch stays the same in this case but hour will change

I think with all those then we have pretty good time and tz support. The last two are especially critical for anybody trying to do the right thing with timezones and scheduling.

IE, if you collect both a tz from a user and the hour they want reminders, you would set the relative campaign date with something like:
  `@(SET_TZ(SET_TIME(NOW(), flow.time), flow.timezone))`

I guess to be totally complete we should just bite off the same kind of methods for dates honestly.

Some of this will get slightly simpler when we have first class support for contacts having their own timezones but I don't think the requirement to have these goes away.

**Comment by nicpottier** [comment]
Oh for each type we should also have `FORMAT_` versions. For time that would be an am/pm representation if the org is set that way, for those on 24 hour would get rid of leading zeros.

For TZ, probably no difference so probably not needed.

**Comment by rowanseymour** [comment]
I think that all makes sense. Re the question of whether we add a new type - I think it would help on our side and users wouldn't be aware of it unless we added something like contact field of type TIME. There are other types like ARRAY which we use internally but always get stringified before they get to the user.

I think for now - just to fix current flows, and correct me if I'm missing something - I can punt on timezone support but I'd agree that's a missing piece. I really like the idea of making the whole date/time thing so much easier in v2 as that's been a constant pain point in legacy expressions.

One little thing I'm not sure about `set_` as verbage for a function that doesn't actually modify the argument passed to it. `replace_time` and `replace_tz`?

**Comment by nicpottier** [comment]
Agree TZ can wait until new editor launch.

Replace feels really verbose to me and doesn't `replace_` have the same connotation? I mean there has to be something you are replacing so it feels like a modifier as well. Expressions are purely functional aren't they? Is there ever a place where an expression can change state? Feels like `set_` isn't super ambiguous if not.

Other ideas.. `at_time`? weirder for the tz case in that the difference between `in_tz` and `at_tz` is even vaguer.  `to_time`? `

**Comment by rowanseymour** [comment]
Expressions are completely functional., and to me `set_` sounds very unfunctional.. `replace_` or `change_` are at least ambiguous. I will concede `set` being 3 letters long is nice.

`in_tz` sounds nice too.. I dunno how useful it is to force that into a consistent verbage. Right now we have a lot of functions like...

* `has_`
* `parse_`
* `format_`

Also right now `text()`, `number()`, `datetime()`, `boolean()` are all conversion functions rather than constructors, and we have the somewhat awkwardly named `datetime_from_parts()` to create a datetime from year, month. That would suggest `time()` is a conversion and `time_from_parts()` is the constructor. Does `time(now())` get the current time?

We haven't saved a new flow definition yet so now's the time to hammer out naming these things!

@ericnewcomer @norkans7 @dodobas ?

**Comment by dodobas** [comment]
the way we(at previous company) worked with time/date data was along the lines of:
* a single expression `at(_whaterver_)` that converts number/string to datetime
* had support for `+` and `-` operators which worked with duration like: 1second, 34weeks, 5hours

in a nutshell, an expression would look like `at("2018-12-12") + '3 months'` 

everything was internally in UTC, and users could get a representation in any TZ, using an expression like ... `'datetime_intz(at(cur_timestamp), "US/Pacific")'`

**Comment by rowanseymour** [comment]
@dodobas FYI legacy expressions support date operations with + and - but we decided to replace those with more explicit function calls in new expressions. It's hard to refactor expressions when you can only know the types of things at runtime. So `@(now() + 1)` becomes `@(datetime_add(now(), 1 "D"))`, and +/- are reserved soley for numerical arithmetic.

**Comment by rowanseymour** [comment]
Addressed in #519
