### ISSUE TITLE
Flexible date vs datetime arithmetic?

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#532]
`@date.today` in a legacy expression is an org formatted date, e.g. 21-02-2019

For date arithmetic, we parse the left hand-side as a date or a datetime - i.e. get back one of those depending on whether the text contains a time component.

So `@(date.today + 1)` parses into a date + 1day, returns a date
So `@(date.now + 1)` parses into a datetime + 1day, returns a datetime

In the new engine all date arithmetic goes thru `datetime_add` which returns a datetime even if passed a date. So migrated expressions like `date.today + 1` are coming back as full ISO datetimes... which is maybe not the end of the world... in the new world.. where you can cast that back to a date with `date()` or format it as a date with `format_date`... but it's a problem for migrated expressions.

**Comment by rowanseymour** [comment]
I think my preference is to keep things explicit in the new world and use `legacy_add` to match the automagical old world behavior

**Comment by nicpottier** [comment]
Can't our migration cast to date in the case where they use `today`?

I definitely don't want to keep the add behavior. It always felt like a parlor trick and now that we have real adding for date we really don't need it. (IE, people are doing `+ 30` when really they almost certainly want `date_adde(foo, 1, "M")`

**Comment by rowanseymour** [comment]
Ok I think we're on the same page about not messing with how `datetime_add` currently works, but we're still left with the problem of migrating something like `@(date.today + 1)`. We need to both:

1. Produce a date value - could achieve that via `legacy_add` or wrap the result of `datetime_add` with `date`
2. Format a date value - in legacy expressions - we changed datetimes to stringify as ISO.. but.. and I think this was just an oversight.. we left dates stringifying as org-formatted. 

So the migration would have to know that an expression is producing a date value, and then wrap the result in `format_date`.

**Comment by nicpottier** [comment]
Ya.. I think we can do that if we detect one of the arguments is `today`. May not be perfect but should be close no?
