### ISSUE TITLE
Add UUID field to sessions

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#536]

**Comment by rowanseymour** [comment]
Did another great job of documenting this issue. @nicpottier is this still something that would be useful in mailroom?

**Comment by nicpottier** [comment]
Ya we did. Doh.

I mean from a consistency perspective it sounds nice for sure in that most everything else has UUIDs, but that doesn't seem like reason enough. I guess one nice thing would be that that might prevent a double insert from a mailroom bug if we had a unique constraint on it and that sounds like a positive probably?

**Comment by rowanseymour** [comment]
Yeah and from the RP database POV it would be nice for sessions to be referenceable by UUID like almost everything. Let's do it.

**Comment by rowanseymour** [comment]
Added in #740
