### ISSUE TITLE
Simplify migrated date/time expressions

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#546]
We should discuss how much effort is worth putting into this, but it would be possible to simplify the migration of some date/time arithmetic expressions by looking out for certain patterns. For example right now 

`@(date.today + 5)` 

migrates to 

`@(format_date(datetime_add(format_date(today()), 5, "D")))`

because `date.today` migrates to `format_date(today())` and `@(<DATE> + 5)`  migrates to `@(format_date(datetime_add(<DATE>, 5, "D")))`

but it would work in the new syntax as just:

`@(format_date(datetime_add(today(), 5, "D")))`

**Comment by nicpottier** [comment]
I don't think worth it, though something we should add to the list of things to chat about when we flip to new editor. (IE, "Vari^D^D^D^DImprovements in New Engine")
