### ISSUE TITLE
Default values for Numeric contact fields

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#555]
Proposal:
  `@contact.age` should be 0 if unset.

Would allow for `@(contact.age + 1)` which is fantastically annoying for people to do without having a global contact initializer.

I figure if most people don't want to use pointers to ints when programming we should be the same for flows.

**Comment by nicpottier** [comment]
(this also matches our new behavior (mostly) for text contact fields, IE: `@(contact.fields + "foo")`

**Comment by rowanseymour** [comment]
There are two ways to fix this

1. `@contact.fields.age` actually evaluates to zero
2. `NULL` acts like zero in arithmetic

I think I prefer 1. but there may be implications for distinguishing between implicit and explicit zeros.

**Comment by nicpottier** [comment]
I *think* I agree that this only applies to contact fields. Only other case I could think of where a typed value would be used in addition would be say a webhook result. Having a `{"num": null}` webhook result work with something like `@(results.webhook.extra.num + 1)` actually return 1 seems wrong.

**Comment by rowanseymour** [comment]
The excellent google doc says `null` and `""` should always numberify as zero but I started implementing that and things got weird quickly. I can convince myself it's ok in arithmetic but in other places where we numberify it feels like this would just silence things which are clearly errors, e.g.

```
@(contact.urns[""]))
@(contact.groups[results.webhook.extra.num])
@(word(input.text, ""))
```

So I think I'm still leaning toward option 1 above where its just that an unset contact field of type number essentially has a default of zero (and not that it makes much difference but a field of type text would default to `""` instead of `null`)

**Comment by rowanseymour** [comment]
After discussion with @nicpottier - for now we'll keep nulls and contact fields as they are - and users will have to use `@(default(...))`

**Comment by chris-erickson** [comment]
@rowanseymour I apologize if this is the wrong place though it seems related.   Previously, empty contact fields would be put into a webhook as `""` (empty string) by way of the splitting method for building the POST body.  It seems that in the new webhook body builder 🏋️‍♀️, you get a javascript `null` instead.  So we are using `"from_address2", default(fields.address_2, ""),` for now, but don't want to propagate this to all our flows or validator endpoints that are expecting `""` unless this is considered a permanent change.

This new webhook experience is just awesome, btw.

**Comment by nicpottier** [comment]
Ya, current behavior is going to remain for the medium term at the very least. I think `null` is definitely the right thing to return there in webhooks, especially for a string field.

**Comment by rowanseymour** [comment]
To clarify, this behavior only applies to JSON converstions. So if you have a field called age which isn't set, then

`@fields.nickname` &rarr; ` `
`@(json(fields.nickname))` &rarr; `null`

**Comment by chris-erickson** [comment]
Great, thanks.
