### ISSUE TITLE
Shorter reference for `@contact.fields`

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#556]
We are moving from `@flow` to `@results` which isn't so bad for peeps.

But we are also moving from `@contact.age` to `@contact.fields.age` which feels rather annoying to me as one of the things people use the most in their flows. Should we consider something shorter?

Just `@fields.age`? Understand there's some ambiguity for parent contacts etc, but that's a 1% use case if that.

**Comment by nicpottier** [comment]
Or go crazy with `@c` as a shortcut for `@contact` .. having two names may be confusing.

Others here are: `@contact.urns` which is a common one. `@urns`?

**Comment by nicpottier** [comment]
Though I don't hate `@contact.tel` which is what the most common case is.

**Comment by rowanseymour** [comment]
I've talked myself around on `@fields.*` (and I guess `@urns.*`). I think that's less confusing than `@c` because that introduces two names at the same level for the same thing - it becomes unclear if after typing `@c` we would auto-complete `@contact` or `@c`... and if it's not `@c` how would iusers even discover that.

**Comment by nicpottier** [comment]
While we are at it, how do we feel about `@extra.foo` for a webhook result now being instead `@results.webhook.extra.foo`?

**Comment by nicpottier** [comment]
While we are at it, is `extra` the right name here? Should it be `data`?

**Comment by rowanseymour** [comment]
Had a thought about this.. and well until we start saving new flow definitions, we may as well put all options on the table.

To me `@contact.fields.age` isn't actually a problem. It's easy for a user to look at that and know what it means - the `age` `field` on the `contact`. Our problematic expressions are those like:

`It's on  @(format_date(datetime_add(contact.fields.joined, 7)))`

Even just writing I had to pause for a bit to count my parentheses and make sure they balance. And just shortening the context references doesn't do anything to make that expression easier to write or understand:

`It's on @(format_date(datetime_add(fields.joined, 7)))`
`It's on @(format_date(datetime_add(c.f.joined, 7)))`
`It's on @(f_d(d_a(c.f.joined, 7)))`
`It's on @( ✨(🗓️(👤.📛.joined, 7)))`

What might help is if we weren't using parentheses both inside the expression and for the embedding of the expression inside the template... perhaps `@{...}` or just `{...}`...

`It's on { format_date(datetime_add(contact.fields.joined, 7)) }`

and maybe also having a generic, type aware `format` function...

`It's on { format(datetime_add(contact.fields.joined, 7)) }`

and perhaps one day some basic syntax highlighting...

<img width="686" alt="captura de pantalla 2019-03-03 a la s 09 54 02" src="https://user-images.githubusercontent.com/675558/53696993-65948180-3d9a-11e9-87d6-e6c166f7566a.png">

**Comment by rowanseymour** [comment]
Added in #595
