### ISSUE TITLE
LegacyAdd doesn't consider DST changes

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#570]
May also be a problem elsewhere. Need to make sure dates are converted into `env.Timezone()` before any manipulation

**Comment by rowanseymour** [comment]
Need to check what the expectation here is...

Example: California skipped an hour after 2am on 2019-03-10 this year.

So if we have a datetime **2019-03-10T01:00** in that timezone, and we travel forward 24 hours... we actually arrive at **2019-03-11T02:00**. 

But if we're asked to add 1 day.. doesn't that still mean shift by a day and keep the same time value? I.e.

```
datetime_add("2019-03-10T01:00", 3, "h")  => 2019-03-11T05:00
datetime_add("2019-03-10T01:00", 24, "h") => 2019-03-11T02:00
datetime_add("2019-03-10T01:00", 1, "D")  => 2019-03-11T01:00
datetime_add("2019-03-10T01:00", 1, "W")  => 2019-03-17T01:00
```

If that's the case, then it seems that `legacy_add` is currently correct because it only supports addition of whole days, and it's not changing time, i.e.

```
legacy_add("2019-03-10T01:00", 1) => 2019-03-11T01:00
```

**Comment by rowanseymour** [comment]
Added some tests which assert current behavior in 867c7a597acdd79baecac01f6f0828b6b25c4d00

**Comment by nicpottier** [comment]
Wish we had recorded more details about the bug when we saw it. Do agree this seems right (day adds should retain logical hour) but we wouldn't have filed this if everything was working as expected right?

**Comment by rowanseymour** [comment]
Yeah all I can imagine is that there was something wrong but it wasn't `legacy_add` at fault 😬 Trying to think where else we do date addition...

**Comment by nicpottier** [comment]
We'll know November 4th.

**Comment by rowanseymour** [comment]
Yeah. Ok well closing this for now and at least there's now some tests which assert/explain current behavior.

**Comment by nicpottier** [comment]
I vaguely remember issues around basically losing timezone information which was needed to interpret these correctly, but I honestly can't remember the details and it sure seems like the behavior above is right. So ya, let this be a lesson to us to make more detailed issues, especially for tricky bits like this.
