### ISSUE TITLE
Excellent2 Manifesto

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#578]
Types in Excellent are a superset of JSON, any Excellent type can be represented in JSON.

Available types:
 1. numbers - internally represented as decimals. ex: `1`, `1.45`, `1E10`?
 2. dates - any string that looks like an ISO8601 date in the format ex: `2019-03-14T22:24:28+0000`
 3. locations - any string that is a valid location in the org and in our format ex: `country > state`
 4. strings - any string that is not one of the above ex: `hello`
 5. urns - any string that looks like `scheme:path[#arst]` where scheme is one of our supported schemes
 6. arrays - can be composed of any of the above, can be mixed types
 7. maps - keys are strings, values can be any type

Key piece if it looks like a date, it is a date, same for location etc..

Each type has a "formatted" version. That is the default representation when stringified, IE, when appended with another string or included in a template. 

Examples:
 1. `Now is @("2019-03-14T22:24:28+0000")` turns into org formatted date
 2. `You like @(["Pizza", "Beer"])` turns into `You like Pizza, Beer`
 3. `You live in @("USA > Washington")` turns into `You live in Washington`

Whether we `format` a value is determined by context. If you are appending a date to a string, then the value will be formatted first. This includes it being substituted in a template.

If a value stands alone, say in set contact field action it is not by default formatted. So the expression `@contact.dob` resolves to `2019-03-14T22:24:28+0000` if it is the only text in a reply action or a set field action.

If you want a value to be formatted (and stand alone) you can call `@(FORMAT(..)))` on it.

**Comment by ericnewcomer** [comment]
Couple tiny clarifying assumptions..

> If a value stands alone..

after trimming whitespace

> If you want a value to be formatted (and stand alone)...

`@(FORMAT(results.foo))` is always equivalent to `@("" + results.foo)`

**Comment by rowanseymour** [comment]
How would you embed an ISO date in a template (e.g. webhook payload) ? Any anything really in its canonical rather than formatted version?

**Comment by ericnewcomer** [comment]
If `JSON()` isn't enough maybe we could have a complexifier method

**Comment by rowanseymour** [comment]
Well JSON returns an actual string literal with quotes for most things, but the challenge here is that even if you add `complexifier` method, and it returns an ISO date... you're saying that _IS_ a date and ends up being pretty formatted again.

Frankly, my initial feeling (having only given this minutes worth of thought) is excitement at the prospect of auto-formatting and fear at the prospect of auto-parsing. One crazy idea is that `@(...)` expressions pretty format their result and `$(...)` expressions don't.

**Comment by nicpottier** [comment]
I really like the idea of `$...` being non formatted. I *really* want it to always be a JSON value. That is in the case of a simple string, the quoted string, ie, not just `USA > Washington` but `"USA > Washington"`. I want that because I want the array case to be consistent `["USA > Washington"]`.

But you then run into problems in how you get say an *unquoted* ISO date into a template.

Which makes me want to backtrack entirely and say you do have to call `@(FORMAT(fields.dob))` if you want a pretty date and `@fields.dob` returns `1977-06-2312:23:12Z`. Maybe I make myself feel better by saying we introduce `@(F(fields.dob))` as shorthand.

And we stay on the path we've been on in that we introduce a few convenience variables for the most used things, like `@contact.urn` returning the *formatted* urn so people don't need to deal with it. I mean the good thing with that is that people quickly look for the solution when they get an ISO date back and fairly quickly seem to discover `FORMAT_` to deal with that case.

**Comment by nicpottier** [comment]
The good thing with the above is there is less magic and more predictability for a user. `$()` ALWAYS returns JSON, `@()` always returns plain strings and variables are always their typed representation unless you decide to format them. The behavior is consistent regardless of whether your template stands alone or is part of something else.

I would also argue that I'd like the `$()` and `@()` representation to always be of the same structure. That is if `@contact.urns` returns `tel:12067799294, twitterid:12355` then `$contact.urns` returns `["tel:+12067799294", "twitterid:12345"]`. 

If we want exploded things, then you cast to a map first or we have an `EXPLODE` or `DETAILS` or `EXPAND` function that returns an array of maps.

Which would then be:
`@(EXPAND(contact.urns))` -> `scheme: tel, path: 12067799294, scheme: twitterid, path:12345`
`$(EXPAND(contact.urns))` -> `[{"scheme": "tel", "path":"12067799294"},{"scheme": "twitterid", "path": "12345"}]`

**Comment by nicpottier** [comment]
`FORMAT` on a list returns the formatted version of a lis with the formatted version of each value.

So `@(FORMAT(contact.urns))` returns `(206) 779 9294, nicpottier`

**Comment by nicpottier** [comment]
Other things...

Can we make it so that `EXPAND` or whatever it is, always mirrors the context, even if that is wasteful and repetitive? And then say we deal with this later on by having some functional methods to filter keys out of a map?

I feel like that's the only sane thing from a user's perspective and just generally makes sense. Ok, I can walk this tree using dot notation (or arrays) and if I want I can just get the exploded view as well. Maybe that explosion function should have a name related to context?

**Comment by nicpottier** [comment]
Type | @ value | JSON value | FORMAT
-----|---------|-------------|----------
number|32.12|32.12|32.12
date|`2019-03-15T06:57:45.705546-07:00`|`"2019-03-15T06:57:45.705546-07:00"`| `15-03-2019 06:58`
urn|`tel:%2012067799294` `twitterid:12345#nicpottier`|`"tel:%2012067799294"` `"twitterid:12345#nicpottier"`|`(206) 779 9294` `nicpottier`
location|`USA > Washington` | `"USA > Washington"`|`Washington`
string|`hello world`|`"hello world"`|`hello world`
arrays|`[1,2,3]` `[pizza, beer]`|`[1,2,3]` `["pizza", "beer'] | `1,2,3` `pizza, beer`
maps|`{key: value, key2: value2}`|`{"key": "value", "key2", "value2"}`|`key: value
key2: value2`

**Comment by nicpottier** [comment]
Guiding principles for the above:
 1. We don't want lists acting differently (say succeeding as a parameter) when being passed to a function when the have a single item vs many items
 2. It should be obvious from an `@` representation what type something is, in the ambiguous cases `@(JSON(..))` should settle it for sure
 3. No fancy JSON formats, instead new method to explode complex types (which you can then either FORMAT or index into or whatever, those return one of the primitives above)
 4. No auto casting of lists (because we want things to break the first time, not when things change)
 5. For convenience we may provide singular versions in the context.. ex: `@contact.urn` which is a formatted version of the first `urn` but that doesn't violate above (it is returning a `string`)

**Comment by nicpottier** [comment]
Context | JSON VALUE | Explode Value | Comments
---------|--------------|--------------|------------
@contact | `"Nic Pottier"` or `""` | `{"uuid": "arst", "name": "Nic Pottier", "urns": [...], "fields": [...]..}` | For ease of use in the common case of addressing a contact by name
@contact.urn | `"(206) 779 9294"` | -- | Convenience shortcut for formatted highest priority URN
@contact.urns | `["tel:%2B12067799294"]` | `[{
