### ISSUE TITLE
Everything is a primitive

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#591]
Currently in Excellent2:

- Everything in the context has to be an `XValue`
- We have a set of "primitives" (`XPrimitive` which extends `XValue`) that live in `excellent/types` which have a set of conversion routines and can be used in function calls etc.
- Complex objects (e.g. contact, input) can implement `XValue` 
  - they control how they stringify, JSONify etc (e.g. contact stringifies as its name)
  - they have to be able to reduce themselves to a `XPrimitive` to be used by functions etc

However we'd like everything in the context to behave like a "primitive", i.e. `@contact` should behave like an `XMap`, `@contact.groups` should behave like an `XArray` etc.

One way to approach this is that a `Contact` instance is still an XValue, but that it reduces to a map, and shouldn't do any customization of `ToXText`, `ToXJSON` etc.

But another way would be to say that only the basic Excellent types can exist in the context, i.e. `@contact` is just an `XMap` and it's guaranteed to always behave exactly like one. Likewise `@contact.groups` is just an `XArray`. This would do away with the need for complex objects to reduce themselves to primitives - in fact it would do away with the idea of complex vs primitives altogether. Everything in the context is just one of the basic Excellent types.

The only gotcha is needing a way to lazily populate the context.. which itself will just be an `XMap`. But I think that's easily solved with a utility type.. which implements `XValue` but proxies something else that it fetches lazily, e.g.

```golang
type XLazy struct {
  value XValue
  fetch func() XValue
  ...
}

func(x *XLazy) ToXText() XText  {
  // .. fetch value ..
  return x.value.ToXText()
} 

var _ XValue = (*XLazy)(nil)
```

and then the context looks something like...

```
NewXMap{
    "contact": NewXLazy(run.Contact().Context)
    "urns": NewXLazy(run.Contact().URNContext)
    ...
}
```

Where `Contact::Context()` is a function that returns an `XMap` representation of the contact. Contact itself doesn't define `ToXText` or any other of the `XValue` methods.

**Comment by nicpottier** [comment]
I'm fine with this though it does remove any possibility of "escape hatching" out of an Excellent function by looking at things that don't exist in the form we want in the context. That may be an ok thing to do (we can always change our mind later) but just figured it was worth saying. Also makes this refactor a lot bigger :)

**Comment by rowanseymour** [comment]
Yeah.. we've come this far without escape hatching and currently all the excellent stuff resides in a top-level module which knows nothing of the engine's complex types. I feel pretty good about the decision that things like `@contact` shouldn't have any special behavior and I think this refactor will cement that, and ultimately simplify things.

Workwise the nice part is that we can add `XLazy` (?) and convert complex objects over one by one until there are none-left and then `XPrimitive` and the whole `Reduce` method become redundant.
