### ISSUE TITLE
map vs dict vs object terminology

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#597]
Language | Name
-|-
Python | `dict`
Java | `Map`
Javascript/JSON | `object`
Typescript/ES6 | `Map`
Golang | `map`
VB.Net / C# | `Dictionary`
PHP | `array` 🤷‍♀️ 

🗳️ vote now!

**Comment by nicpottier** [comment]
A bag of maps just doesn't have the same ring to it.

I'm fine with either `dict` or `map`, with a slight preference to dict only because it isn't a verb like map is.

**Comment by nicpottier** [comment]
Also I think to untechnical users dictionary makes more sense than a map. When you say map to someone, they think more of geography. A dictionary being a lookup of items I think is more natural.

**Comment by rowanseymour** [comment]
I'm fine with `dict`. Maybe `map` has more traction in newer languages? @ericnewcomer thoughts?

**Comment by ericnewcomer** [comment]
`dict` works for me.

**Comment by rowanseymour** [comment]
Switched to `XDict` / `dict` in #598

**Comment by rowanseymour** [comment]
We got talking about this again today.. and now that everything in the context is a primitive.. I'm leaning toward `object`

- `array` and `object` is JSON/Javascript terminology
- things like `@contact` are objects with properties to the user and I think that's how they might be presented in the UI, i.e. autocomplete should visually different (maybe with icon) things that return properties vs things that are going to render as an object/dict/map

**Comment by rowanseymour** [comment]
Gone with objects/properties terminology for now
