### ISSUE TITLE
Function name audit

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#634]
|Summary                                      |Signature                                                                                           |
|---------------------------------------------|----------------------------------------------------------------------------------------------------|
|abs(number)                                  |Returns the absolute value of `number`.                                                             |
|and(values...)                               |Returns whether all the given `values` are truthy.                                                  |
|array(values...)                             |Takes multiple `values` and returns them as an array.                                               |
|attachment_parts(attachment)                 |Parses an attachment into its different parts                                                       |
|boolean(value)                               |Tries to convert `value` to a boolean.                                                              |
|char(code)                                   |Returns the character for the given UNICODE `code`.                                                 |
|clean(text)                                  |Strips any non-printable characters from `text`.                                                    |
|code(text)                                   |Returns the UNICODE code for the first character of `text`.                                         |
|count(value)                                 |Returns the number of items in the given array or properties on an object.                          |
|date(value)                                  |Tries to convert `value` to a date.                                                                 |
|date_from_parts(year, month, day)            |Creates a date from `year`, `month` and `day`.                                                      |
|datetime(value)                              |Tries to convert `value` to a datetime.                                                             |
|datetime_add(datetime, offset, unit)         |Calculates the date value arrived at by adding `offset` number of `unit` to the `datetime`          |
|datetime_diff(date1, date2, unit)            |Returns the duration between `date1` and `date2` in the `unit` specified.                           |
|datetime_from_epoch(seconds)                 |Converts the UNIX epoch time `seconds` into a new date.                                             |
|default(value, default)                      |Returns `value` if is not empty or an error, otherwise it returns `default`.                        |
|epoch(date)                                  |Converts `date` to a UNIX epoch time.                                                               |
|extract(object, properties...)               |Takes an object and extracts the named property.                                                    |
|extract_object(object, properties...)        |Takes an object and returns a new object by extracting only the named properties.                   |
|field(text, index, delimiter)                |Splits `text` using the given `delimiter` and returns the field at `index`.                         |
|foreach(values, func, [args...])             |Creates a new array by applying `func` to each value in `values`.                                   |
|format(value)                                |Formats `value` according to its type.                                                              |
|format_date(date, [,format])                 |Formats `date` as text according to the given `format`.                                             |
|format_datetime(datetime [,format [,timezone]])|Formats `datetime` as text according to the given `format`.                                         |
|format_input(urn)                            |Formats `input` to be the text followed by the URLs of any attachment, separated by newlines.       |
|format_location(location)                    |Formats the given `location` as its name.                                                           |
|format_number(number, places [, humanize])   |Formats `number` to the given number of decimal `places`.                                           |
|format_results(urn)                          |Formats `results` to be name and value pairs, separated by newlines.                                |
|format_time(time [,format])                  |Formats `time` as text according to the given `format`.                                             |
|format_urn(urn)                              |Formats `urn` into human friendly text.                                                             |
|if(test, value1, value2)                     |Returns `value1` if `test` is truthy or `value2` if not.                                            |
|is_error(value)                              |Returns whether `value` is an error                                                                 |
|join(array, separator)                       |Joins the given `array` of strings with `separator` to make text.                                   |
|json(value)                                  |Returns the JSON representation of `value`.                                                         |
|left(text, count)                            |Returns the `count` left-most characters in `text`                                                  |
|lower(text)                                  |Converts `text` to lowercase.                                                                       |
|max(numbers...)                              |Returns the maximum value in `numbers`.                                                             |
|mean(numbers...)                             |Returns the arithmetic mean of `numbers`.                                                           |
|min(numbers...)                              |Returns the minimum value in `numbers`.                                                             |
|mod(dividend, divisor)                       |Returns the remainder of the division of `dividend` by `divisor`.                                   |
|now()                                        |Returns the current date and time in the current timezone.                                          |
|number(value)                                |Tries to convert `value` to a number.                                                               |
|object(pairs...)                             |Takes property name value pairs and returns them as a new object.                                   |
|or(values...)                                |Returns whether if any of the given `values` are truthy.                                            |
|parse_datetime(text, format [,timezone])     |Parses `text` into a date using the given `format`.                                                 |
|parse_json(text)                             |Tries to parse `text` as JSON.                                                                      |
|parse_time(text, format)                     |Parses `text` into a time using the given `format`.                                                 |
|percent(number)                              |Formats `number` as a percentage.                                                                   |
|rand()                                       |Returns a single random number between [0.0-1.0).                                                   |
|rand_between()                               |A single random integer in the given inclusive range.                                               |
|read_chars(text)                             |Converts `text` into something that can be read by IVR systems.                                     |
|regex_match(text, pattern [,group])          |Returns the first match of the regular expression `pattern` in `text`.                              |
|remove_first_word(text)                      |Removes the first word of `text`.                                                                   |
|repeat(text, count)                          |Returns `text` repeated `count` number of times.                                                    |
|replace(text, needle, replacement)           |Replaces all occurrences of `needle` with `replacement` in `text`.                                  |
|replace_time(datetime)                       |Returns a new datetime with the time part replaced by the `time`.                                   |
|right(text, count)                           |Returns the `count` right-most characters in `text`                                                 |
|round(number [,places])                      |Rounds `number` to the nearest value.                                                               |
|round_down(number [,places])                 |Rounds `number` down to the nearest integer value.                                                  |
|round_up(number [,places])                   |Rounds `number` up to the nearest integer value.                                                    |
|split(text, delimiters)                      |Splits `text` based on the given characters in `delimiters`.                                        |
|text(value)                                  |Tries to convert `value` to text.                                                                   |
|text_compare(text1, text2)                   |Returns the dictionary order of `text1` and `text2`.                                                |
|text_length(value)                           |Returns the length (number of characters) of `value` when converted to text.                        |
|time(value)                                  |Tries to convert `value` to a time.                                                                 |
|time_from_parts(hour, minute, second)        |Creates a time from `hour`, `minute` and `second`                                                   |
|title(text)                                  |Capitalizes each word in `text`.                                                                    |
|today()                                      |Returns the current date in the environment timezone.                                               |
|tz(date)                                     |Returns the name of the timezone of `date`.                                                         |
|tz_offset(date)                              |Returns the offset of the timezone of `date`.                                                       |
|upper(text)                                  |Converts `text` to lowercase.                                                                       |
|url_encode(text)                             |Encodes `text` for use as a URL parameter.                                                          |
|urn_parts(urn)                               |Parses a URN into its different parts                                                               |
|weekday(date)                                |Returns the day of the week for `date`.                                                             |
|word(text, index [,delimiters])              |Returns the word at `index` in `text`.                                                              |
|word_count(text [,delimiters])               |Returns the number of words in `text`.                                                              |
|word_slice(text, start, end [,delimiters])   |Extracts a sub-sequence of words from `text`.                                                       |

**Comment by rowanseymour** [comment]
Some patterns we've kinda observed for now but are worth discussing:

 * `<typename>` are casting functions, e.g. `text(value)`, `number(value)`
 * `x_from_parts` multi-value constructors, e.g. `datetime_from_parts`
 * `x_parts` exploding a string into an object, e.g. `attachment_parts`
 * not abbreviating `text_length` `text_compare` vs `text_len` `text_cmp`
 * but some abbreviating, e.g. `tz`

**Comment by nicpottier** [comment]
should `clean` be `strip`?
`read_chars` is weird but can't think of anything better.

Otherwise 👍

**Comment by rowanseymour** [comment]
Python programmer in me has `strip` as trimming whitespace.. which might be a function we want in its own right
