### ISSUE TITLE
Should text length functions be emoji smart?

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#640]
See:
  https://blog.jonnew.com/posts/poo-dot-length-equals-two

`text_length("♥️") == 2` which feels wrong but 🤷‍♂️

**Comment by rowanseymour** [comment]
I think i'd lean toward just matching JS here. It looks weird but maybe the user actually needs to know that is two characters.

**Comment by nicpottier** [comment]
Ya, I think I agree, that no language really tries to tackle this is probably a sigh that we shouldn't either.
