### ISSUE TITLE
Saving empty flow result fails validation

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/goflow#641]
AttributeError: 'MailroomException' object has no attribute 'f_lineno'

**Comment by rowanseymour** [comment]
That looks like an error from trying to send a different error to sentry.

Does look from the code like we allow saving a result from an expression that has evaluated to blank but you can't have an empty value in an `set_run_result` action.

**Comment by ericnewcomer** [comment]
I thought we had agreed that `set_run_result` could take an empty value to clear it in goflow. Is there any reason we should disallow that? @nicpottier

**Comment by nicpottier** [comment]
Sure seems like we need this, so ya, should fix.

**Comment by rowanseymour** [comment]
Yeah I would expect it to work like `set_contact_field` etc and allow an empty value to actually remove the value set for that key.
