### ISSUE TITLE
RIGHT and LEFT should support negative indexes

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#642]
Seems common for these kinds of things that you want to strip just the first few characters off a string.

Yes you can do that with a combination of `text_length` and `right`, but seems you could also elegantly do it with `right("foo", -2)`

**Comment by rowanseymour** [comment]
What about adding `text_slice` as an equivalent of `word_slice`? I just wonder how likely it would be that anyone ever figures out that the way to strip N chars from the left is to use `right`

**Comment by nicpottier** [comment]
I think slicing / substr is another natural thing, though having negative indexes there would be useful as well. Either way seems like no downside adding support for negative indexes, just one less error condition.

**Comment by nicpottier** [comment]
Playing with this how about we just remove `right` and `left` entirely and just replace with `text_slice` that supports negative indexes?

`right(n)` is just `text_slice(-n)`
`left(n)` is just `text_slice(0, n)`

And then you can madness like `text_slice("foobar", -4, -2)` which gives you `ob`

**Comment by rowanseymour** [comment]
I like this. I suspect `RIGHT` isn't particularly common anyway, and `text_slice` seems more discoverable.
