### ISSUE TITLE
array() as a result and count()

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/goflow#645]
Error calling `count()` on `array()` in a result.

> _error evaluating @(count(results.whatever.value)): error calling COUNT: value isn't countable_

 1. Save a flow result named whatever with the value of `@(array())`
 2. In a subsequent action, send a message with `@(count(results.whatever.value))`

**Comment by nicpottier** [comment]
This isn't meant to work actually, results and fields are strong values, so
when you save that you are just saving the stringified value.

**Comment by ericnewcomer** [comment]
Oh shoot. Right. I guess I knew that. Pretending to be a user it’s disappointing though.
