### ISSUE TITLE
Maybe step limit should be 255 instead of 100?

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#652]
Here's a perfectly valid session that exceeded 100 steps: (org Nicco)
  https://textit.staging.nyaruka.com/flowsession/json/580/

Yes, maybe I'm doing a while loop in:
  https://textit.staging.nyaruka.com/flow/editor_next/4f40dad6-fb7c-4b89-8fd0-0b71d341930c/

But but, its really cool and would be nice to support it!

**Comment by nicpottier** [comment]
Or altenatively, 640 steps because I think there's a famous quote about 640 being enough for anything.

**Comment by nicpottier** [comment]
I refactored a bit which gets around this. If push came to shove I could probably be even more clever by tracking the incremental score which would simplify things further, so maybe 100 steps is the right number after all.

**Comment by rowanseymour** [comment]
Sounds like this Nicco fella wants to upgrade to the Professional Tier with 1000 steps and 500 contact fields...
