### ISSUE TITLE
Defaults for run and trigger in context

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#654]
We currently have these defaults in the context:

| Object           | Default |
|--------------|---------|
|`contact` | name or urn or id |
|`results`| Name: value\n... same as `@flow` in legacy |
|`results.foo` | value |
|`input`| text\nattachments same as `@step.value` in legacy |
|`channel`| name |
|`flow`|  name |
|`test_result`|  true/false |
|`run`|  _none_ |
|`trigger`|  _none_ |
|`fields`| _none_ |
|`urns`|  _none_ |
|`legacy_extra`|  _none_ |

`fields`, `urns` and `legacy_extra` have no obvious default. But seems like `run` and `trigger` could have them. That would have the added benefit of `run` not dumping out a huge blob unless you explicitly want that i.e. `@(json(run))`

Maybe for run it's a contrived value like `<contact-name>@<flow-name>`.. `Bob@Registration`

**Comment by nicpottier** [comment]
Honestly my leaning is towards no defaults unless we have a specific need and/or the shortcut if obvious. I guess I don't share the same concern over someone including `@run` in a flow, that's going to be pretty obvious pretty quickly and is going to be truncated anyways.

I could see `fields` having a similar default as `results` though.

Happy to be outvoted on this.

**Comment by rowanseymour** [comment]
I'm just trying to establish what the logic is for something having a default and another thing not, as we've spent the previous couple of weeks talking about how great it was that everything in the context now looks and behaves the same.

`@run` dumping out 10s of messages worth of data isn't the end of the world until someone starts building logic around what that looks like (maybe they start posting it to a webhook 😬) and then suddenly we can't change it so easily.

If for argument's sake `@run` defaulted to the UUID, then it would be easy in future to change that and migrate `@run` to `@run.uuid`

So I think I would lean toward reducing the complexity of these defaults where appropriate.

**Comment by nicpottier** [comment]
I actually think the default being simpler and being able to be remapped later is a strong arguments, so I'm on board with more defaults.
