### ISSUE TITLE
Struct-level vs semantic validation

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#673]
There are parts of the flow spec that we lean on struct validation with `validate:".."` tags for validation, e.g. `uuid` is required, `node.router.categories` must have at least 1 value. This kind of validation is invoked within `definition.ReadFlow` so you can't actually read a flow that violates one of those constraints. The mailroom validation endpoint will return 400 (bad request) for such a flow definition.

There are other parts where we lean on custom `.Validate` methods on flow objects, e.g. the `remove_contact_groups` action can't both specify `all_groups=true` and have specific groups in `groups`. This kind of flow validation is invoked from `Flow.Validate` and can include checking that dependencies exist for a given org. The mailroom validation endpoint will return 400 for such a flow definition. The mailroom validation endpoint will return 422 (unprocessable entity) for such a flow definition.

Yet from the pov of caller like RapidPro trying to determine if a flow definition is valid... those concepts of validity aren't so different.

So maybe we should defer doing struct level validation until `Flow.Validate` ?  Or leave things as they are and just make mailroom validation return 422 if it can't read the flow?

**Comment by rowanseymour** [comment]
Having thought about this a bit more I think..

* `definition.ReadFlow` should always return a "valid" flow definition _in the current engine version_, i.e. you can pass it v13.x flow JSON and get back a 14.y flow if that's the latest version - you don't have explicitly migrate the flow.
* The returned flow is "valid" in the sense that it is guaranteed to be runnable so this includes tag-based struct-level validation as well as higher-level object validation (i.e. a node's exit's point to actual nodes)
* Checking of dependencies (against session assets) and augmenting the definition with inspection results should be a separate operation - maybe called something different to `Validate`

@nicpottier @ericnewcomer ?

**Comment by nicpottier** [comment]
Ya that all seems reasonable to me
