### ISSUE TITLE
Legacy expression ending in . do not migrate properly

### ISSUE THREAD

**Issue by norkans7** [nyaruka/goflow#698]
@date. is not migrating to @(NOW())

**Comment by rowanseymour** [comment]
I just checked this and `@date.` migrates fine to `@(now()).`. We also recently changed date parsing to ignore a trailing period so that should parse ok as an ISO date... any more clues from the user's flow?

**Comment by rowanseymour** [comment]
Closing as this appears to be unrelated problem
