### ISSUE TITLE
`@results.foo.extra` isn't a thing

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#702]
`extra` only lives on `run.results`, which seems a bit lame. Do these need to be different really? (now that we have `__default__`?)

**Comment by nicpottier** [comment]
(note this is also what was giving Jason trouble, he COULD access the parent / child extra via `parent.run.results.extra.foo`, I thought we didn't pass that through)

**Comment by rowanseymour** [comment]
Schema of `@results`, `@child.results` and `@parent.results` is currently...

- `__default__` => value
- name
- value
- category
- category_localized
- input
- node_uuid
- created_on

whereas schema of `@run.results`,  `@child.run.results`, `@parent.run.results` is currently...

- `__default__` => value
- name
- values
- categories
- categories_localized
- input
- extra
- node_uuid
- created_on

I do feel like those being subtly different is always going to cause some confusion.. two options:

 1.  Just add `@extra` and for now always steer users to `@results`, `@child.results` and `@parent.results`
 2. Merge these to give them the same mega schema..

**Comment by nicpottier** [comment]
My vote is just mega schema it.. having them be subtly different is obviously so confusing that even we are having trouble keeping them straight. We could have auto-complete not advertise the plural cases in the editor to keep some of the simplicity.

**Comment by nicpottier** [comment]
@ericnewcomer ?

**Comment by ericnewcomer** [comment]
I think mega schema, so `value` and `values` are siblings. I think we probably surface all of it though. Would add to the confusion to just omit values if it is a valid thing. We have descriptions right there at least. But ya, can play with how we display it.

I'm all for one MEGASCHEMA to rule them all.

**Comment by rowanseymour** [comment]
Addressed in #708
