### ISSUE TITLE
Expose external_id of incoming message in the flow

### ISSUE THREAD

**Issue by erikh360** [nyaruka/goflow#715]
We'd like to have access to the `external_id` of an incoming message as a variable in the new flow designer. We need it to initiate actions on the incoming message in external apps.

For example if a user needs help, we can label it in the external app and action accordingly:
POST `v1/messages/<external-id>/labels`
{
    "labels": ["needs_help"]
}

I see external_id was already added to the MsgIn object in `goflow` here: https://github.com/nyaruka/goflow/pull/437

**Comment by nicpottier** [comment]
I'm not opposed to this, obviously it may be `null` but seems we can expose it when available and can definitely see the use case. What do you think @rowanseymour ?

**Comment by rowanseymour** [comment]
Yeah I'll make a PR for this shortly

**Comment by erikh360** [comment]
Thanks! @rowanseymour @nicpottier

**Comment by miltontony** [comment]
@nicpottier @rowanseymour appreciate the quick turnaround on this. When is this likely to be released and deployed to Textit.in?

**Comment by rowanseymour** [comment]
This is deployed now on the engine side - but `@input.external_id` won't appear in auto-complete until we update editor https://github.com/nyaruka/floweditor/issues/665
