### ISSUE TITLE
Migration: deal with Python / Golang regex differences for regex tests

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#73]
Could convert regexes like we once did for Java, e.g. https://github.com/rapidpro/flows/blob/master/java/src/main/java/io/rapidpro/flows/definition/tests/text/RegexTest.java#L96

**Comment by nicpottier** [comment]
Wonder whether an audit of our any current tests would help us determine what/if we need to do that at all.

**Comment by rowanseymour** [comment]
Yeah actually I just assumed golang regexes would be more like Java regexes... but seems from playing on https://regex101.com/ that they use the same (?P<..>) syntax for named capture groups
