### ISSUE TITLE
Contact name migration

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/goflow#732]
Migrating this action:
```json
{
	"type": "send",
	"uuid": "1077f29a-fec1-43c7-ab6c-d26e1d4e36c6",
	"msg": {
		"base": "Message text here"
	},
	"contacts": [{
		"id": 99876091,
		"name": "Contact Name",
		"uuid": "fed6bc11-b211-4993-92d8-34c8e8a028d2",
		"urns": [{
			"scheme": "tel",
			"path": "+18605551212",
			"priority": 50
		}]
	}],
	"groups": [],
	"variables": [],
	"media": {}
}
```

Results in the following action:

```json
{
	"type": "send_broadcast",
	"uuid": "1077f29a-fec1-43c7-ab6c-d26e1d4e36c6",
	"contacts": [{
		"uuid": "fed6bc11-b211-4993-92d8-34c8e8a028d2",
		"name": ""
	}],
	"text": "Message text here"
}
```

Is this by design? The new editor does not populate contact names from uuids so we end up with a broken looking flow.

**Comment by rowanseymour** [comment]
I just added a test to check this works at https://github.com/nyaruka/goflow/blob/master/legacy/testdata/actions.json#L397

I suspect we're actually migrating a version of the legacy flow that doesn't have those contact details - i.e. wasn't run thru `Contact.as_json(expand_contacts=True)`

**Comment by ericnewcomer** [comment]
Perhaps this bug is more on RP making sure that expand_contacts is true when sending off to goflow for migration.

**Comment by rowanseymour** [comment]
Moving this over to https://github.com/rapidpro/rapidpro/issues/1006
