### ISSUE TITLE
Should `trigger.params` always be non-null?

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#738]
Spawned from: https://github.com/nyaruka/null/pull/3

Just adding here so we can record the conversation and resulting conclusion.

I'm not super passionate either way but I do think it is somewhat awkward that a flow other that wants to do say a "Split by expression" on say a trigger param of "source" or the like, has to do something like:
  `@(IS_ERROR(trigger.params["source"], "none"))`

Instead of just being able to do:
  `@(trigger.params["source"])`

Admittedly contrived.

I guess the question to me is whether the distinction of params being `null` is useful to the flow author and if not then why ever expose it? 
/note: this is not advocating making all null JSON keys act the same as an empty JSON dict, it is just saying that `trigger.params` is always an empty dict if `null` is passed in, ie it is a context change not a type change/

**Comment by rowanseymour** [comment]
I'm fine with this. Note that in goflow we've thus far said that `trigger.params` is any valid JSON (`null`, `2.3`, `"foo"`), but in practice (I think) we only allow users to provide this via the RP API runs endpoint, and that requires it to be a dict. So we could be even stricter and say `trigger.params` _is always a JSON object_.

**Comment by nicpottier** [comment]
Seems a lot saner to say that to me. In theory someone could pass in a literal `null` as well which seems nuts.

**Comment by rowanseymour** [comment]
As of #741, it's non-null for trigger types that can take params
