### ISSUE TITLE
Validation errors don't always snakify field names correctly

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#74]
E.g. I keep seeing `start_flow: field 'uui_d' required`

**Comment by nicpottier** [comment]
ya, Eric saw this.. almost certainly my hack here is shitty and needs more cleverness:
  https://github.com/nyaruka/goflow/blob/master/utils/validator.go#L49

**Comment by rowanseymour** [comment]
Working on a fix that uses reflection to lookup the actual json field name from the tag
