### ISSUE TITLE
Asset caching and lazy loading

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#75]
We need a solution that:

- Avoids the caller needing to sending flow (etc) definitions with every request
- Supports location data being an asset type and thus solves https://github.com/nyaruka/goflow/issues/71
- Allows the caller to provide an up-to-date definition when necessary, e.g. the simulator needs to run with the absolute latest version of a flow

One option would be something similar to `<script>` and `<style>` elements in HTML where they can be embedded resources, or linked resources.

```json
"assets": [
  {"type": "channel", "uuid": "7a3b...", "src": "http://rpd.io/as/flows/7a3b..."},
  {"type": "flow", "uuid": "4af6...", "src": "http://rpd.io/as/flows/4af6..."},
  {"type": "flow", "def": {
    "uuid": "a9c6...",
    "nodes": [...]
  }},
]
```

So in the simulator case, it would send flows as embedded definitions, but probably all real world use we would send just the links. Goflow would then be responsible for caching those definitions for X amount of time.

If we wanted to support longer caching we could give callers the ability to invalidate or update goflow's asset cache when they know something has changed, e.g. an `/assets` endpoint

**Comment by nicpottier** [comment]
So another approach would be the JSONSchema approach of using `$ref` as a marker that the resource should be loaded from a URL:
```
"assets": [
{ "$ref": "https://rpd.io/as/flows/7123..." },
{ "type": "flow", "uuid": "7114...", "name": "..."},
]
```

Not sure this is better, just different..

**Comment by nicpottier** [comment]
Downside of this is you don't know UUID or type or anything ahead of time.

**Comment by rowanseymour** [comment]
Something else to consider - maybe runs (and contacts?) can be assets sometimes. For example in the trigger flow action case - the caller will need to start a flow with a parent run which belongs to a different contact. It may make sense to model this as an asset because:

- It's immutable for the new flow session
- The engine shouldn't be sending it back in the session and the caller shouldn't be trying to sync it.

The way it might works is:

1. The trigger flow action will return a `trigger_flow` (?) event which contains the UUID of the parent run.
2. Caller will grab the output of that run (either immediately from the session output or RapidPro could do it later by loading `FlowRun.output`)
3. Caller starts a new flow session with:
    - That parent as an asset
    - A start_flow event which specifies the parent by UUID

**Comment by nicpottier** [comment]
Ya, I think that sounds right to me, that if a run is not part of a session then it is an asset. So I guess it is that runs belong to the session where they were started, otherwise are assets.
