### ISSUE TITLE
goflow docs should have internal hrefs to individual functions

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#753]
Would make it a lot easier to link to a specific function when helping customers. (could also allow linking from the editor)

**Comment by rowanseymour** [comment]
This already exists so if you're seeing references to functions that aren't lists then I just forgot to make them links. Or is this in editor auto-completions?

Syntax is `[function:lower]` to link to the function called `lower` or `[type:array]` to link to the type `array`

**Comment by nicpottier** [comment]
Hrmm, I was looking at https://textit.in/mr/docs/expressions.html, specifically `format_datetime`

Oh, I see the problem, the `<a>` is empty so it doesn't highlight in the browser for me to click on. Maybe we can make the anchor tag have the actual name in it? Would make linking to it a bit simpler.

**Comment by rowanseymour** [comment]
Not sure what you're looking at.. there is a link to `format_datetime` in a different part of the docs that's not properly formed? 

Above the section for `format_datetime` there is a named anchor `<a name="function:format_datetime"></a>` so you can have URLs like `/expressions.html#function:format_datetime`

**Comment by nicpottier** [comment]
Right, but if you actually put something in the `<a></a>` instead of it being empty then it would show up as a little anchor tag when near it which would allow you to click on it, have the URL append the HREF onto it and let you copy/paste that. As it is there's no easy way to know what the HREF is without looking at the source (or just knowing you need to append `function:` before the function name.

**Comment by rowanseymour** [comment]
Ah ok I get you now - then we have an easy to get the link. So the function name itself is a copy-able link. Makes sense
