### ISSUE TITLE
Re-add simpler datetime extraction functions

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#763]
In new expressions we replaced functions like `year` and `hour` with `format_date(d, "YYYY")` and `format_datetime(d, "tt")`... which is nice in terms of keeping total number of functions down.. but really not as discoverable... especially for users familiar with the old functions.

**Comment by rowanseymour** [comment]
Thoughts @nicpottier @ericnewcomer? What spurred this was a user asking recently where the old `year()` function went and it felt weird to explain it was now `format_date(d, "YYYY")`. I don't think even I would guess to use a format function for something like that.

I don't think limiting the function count is more important that returning the thing the user needs when they type `year` in the auto-complete.

**Comment by nicpottier** [comment]
I don't care a ton though I think my bias would be fewer functions. If you teach them how to fish with `format_` then they get to do any kind of date field extraction, so to me seems like that's the preferred way to go. For `year` it is a bit simpler but for `hour` that could be 12 or 24 hour format for example, which is handled by `format_` nicely.

We are talking fairly advanced usage here so having a bit of a hoop to jump through doesn't bother me.

**Comment by ericnewcomer** [comment]
Ya, all expressions are advanced. Question I guess is how do we teach them to fish. A common patterns article with examples might not be the worse thing.

**Comment by rowanseymour** [comment]
I think the hour thing is good example when `format_x` makes sense and when it doesn't. 

If a user wants to print the hour with AM/PM.. then `format_x` is the natural thing to reach for. You want to take a value and format it as text.. e.g.

```
Hi your appointment is @(format_time(fields.apt, "hh aa"))
```

If a user wants to use the value arithmetically, and I think `format_x` is pretty counter-intuitive, e.g. updating a field value by 1 hour...

```
@(replace_time(fields.apt, time_from_parts(format_time(fields.apt, "tt") + 1, format_time(fields.apt, "mm")))

@(replace_time(fields.apt, time_from_parts(hour(fields.apt) + 1, minute(fields.apt)))
```

Furthermore if they want to something which is type-dependent like JSON payload building, they have to cast as well

```
@json(object("hour", number(format_time(fields.apt, "tt"))))
@json(object("hour", hour(fields.apt)))
```

I know we always strive to make the 90% easy and the 10% do-able but this feels like the wrong balance for the 10% since it doesn't seem discoverable/intuitive for a user.

**Comment by ericnewcomer** [comment]
This feels more like an argument for `dateadd(part, amount)` not `year()`

**Comment by nicpottier** [comment]
Once you are getting into JSON payloads then I don't think we are talking typical users and `format_` still makes sense I think.

Date addition/subtraction should never be done via getting hours and adding or the like, that's always going to end up being wrong for edge cases. So not a strong argument for `hour` there either.

Maybe year is useful, though even then it is a question of two digit vs four digit etc.. I don't know, just pretty meh on this beyond documentation.

**Comment by nicpottier** [comment]
Also in general I tend to prefer languages that have one way of doing things as opposed to many, so perhaps that is informing my bias there.

**Comment by rowanseymour** [comment]
Bad example above since in that specific case you would use `datetime_add` but we've definitely seen date time expressions that aren't simple add/subtract operations.

> Also in general I tend to prefer languages that have one way of doing things as opposed to many, so perhaps that is informing my bias there.

To be clear my argument here is that from a user intention pov.. they're doing different things regardless of whether the output is sometimes the same.

And at some point you have to balance "there can be one way!" with "is this intuitive?" ... for example we could ditch the datetime constructor functions and say you always have to use datetime parsing...

```
time(fields.hour & ":" & fields.minute)

vs

time_from_parts(fields.hour, fields.minute)
```

But clearly outvoted so I'll close this for now.
