### ISSUE TITLE
Lambdas

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#768]
Currently have a user with a webhook payload like:

```json
[
  {"foo": 1, "bar": 2},
  {"foo": 3, "bar": 4},
  {"foo": 5, "bar": 6}
]
```

And they want to render it as

```
1
2
3
4
5
6
```

Our current toolbox of `foreach`, `extract`, `extract_object`, `join` almost gets us there but not quite... or at least I haven't yet figured it out. The basic problem is the transformation of each item in the array can't be described in a single function call.

If `join` took an object and used its values as the array.. it would work but that feels a little obscure - why the values and not the keys, what if the order of properties in the object isn't consistent for each item.

```
@(join(foreach(webhook, join, "\n"), "\n"))
```

If we introduced syntax for lambdas then `foreach` would be able to perform transformations that can't be reduced to a single function call. There are a lot of different syntaxes for lambdas out there that we might want to borrow from...

* Python: `lambda x : 2 * x`
* Ruby: `-> (x) { 2 * x }`
* Coffeescript: `(x) -> 2 * x`
* PHP: `$x ~> $x * 2`

For argument's sake, suppose we borrowed Python's syntax (just cuz I'm pretty sure it would work with our grammar):

```
lambda: "lambda" name ":" expression
```

Then you could do the transformation like:

```
@(join(foreach(webhook, lambda x: x.foo & "\n" & x.bar), "\n"))
```

**Comment by rowanseymour** [comment]
If we really wanted to avoid the addition of new syntax, I suppose you could also solve this by letting `foreach` take arrays as the varargs, i.e.

```
foreach(values, [func1, arg1, arg2], [func2, arg3, arg4], ...)
```

Evaluated as:

```
func2(func1(x, arg1, arg2), arg3, arg4) for x in values
```

But there would still be cases you can't solve and it's arguably just as complex.

**Comment by chris-erickson** [comment]
I think we could make substantial use of this for cases where we iterate a json array, and want to display the top X results in some summarized format:

```
Your nearest polling locations are:

ABC Place
Closes in 1 hour

DEF Place
Closes in 30 mins hour
```

I might be misinterpreting this, but it reminded me of a time not long ago where I felt like I didn't have quite enough of what I needed when building these sequences of results and probably pushed some of that back into the backend code.  That's fine, when we control it..
