### ISSUE TITLE
Localization of functions and completions listings used by the editor

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#799]
Seems easiest way to achieve this would be..

1. Generate the listings as normal
2. Update the individual strings in a set of PO files
3. Generate language specific files from the PO sources, e.g. `functions.pt.json`, `functions.es.json`

Then get the PO files into Transifex

**Comment by rowanseymour** [comment]
@matmsa27 @hudsonbrendon I've gotten this working for function listings and created a new project in transifex which you guys have Reviewer permissions on if you want to have a go at translating those into `pt_BR`. It's these strings...

https://github.com/nyaruka/goflow/blob/master/locales/en_US/flows.po

**Comment by matmsa27** [comment]
Wow, thanks a lot @rowanseymour , certainly we will do this.

**Comment by rowanseymour** [comment]
@matmsa27 updated now to include strings from auto-completion e.g. "the contact name". Bear in mind that there are two things you should not translate:

* any string in ticks like `` `text` `` is a reference to an argument from the function signature which is currently not translated
* any string in braces `{key}` is a placeholder for something the editor will fill in so don't rename those

**Comment by matmsa27** [comment]
Hi @rowanseymour , we had translated 100% of the strings on transifex Flow Engine, but the PR wasn't created here on GoFlow. Do you know what may have happened to PR not being created?

**Comment by rowanseymour** [comment]
I haven't been able to setup automatic syncing in transifex... not sure why but don't see those options for that project.

For now I'll make a PR manually...

**Comment by matmsa27** [comment]
hmmmm, thanks a lot @rowanseymour :)

**Comment by rowanseymour** [comment]
Mailroom will now (see https://github.com/nyaruka/mailroom/pull/332) share docs in all the languages configured in RapidPro - final step is to update the editor to fetch the appropriate docs (see https://github.com/nyaruka/floweditor/issues/898)
