### ISSUE TITLE
Migration of start flow action

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/goflow#802]
In the old editor, we have three different ways to start flows.

1) Enter a subflow and route based on completion or expiration
2) Start a flow (enforced as a terminal action)
3) Trigger somebody (or perhaps yourself) in a flow

In the new editor we don't allow option 2. However, it's possible to get the editor in a state it doesn't recognize by migrating an old definition with such an action. I believe in your discussions this was meant to migrate forward to be like option 1 (this would need to break into its own node if it is in a node with more actions).

Alternatively, we could patch the editor to recognize these types of nodes and handle all the splicing and route manipulation the next time that action is edited. This wouldn't be a hard change on the editor side, but want to pose this question since it feels maybe more right (but more annoying) to fix this in the migration.

**Comment by rowanseymour** [comment]
No. 2 should currently migrate as an enter flow action with `terminal=true`.. we didn't include converting that into a split because the engine migrations weren't in the business of creating new nodes etc. In fact I'm still not sure I would have the engine do that.. seems preferable if we wanted to migrated those to use one last legacy migration.. like when we migrated the old `api` actions to webhook splits

**Comment by ericnewcomer** [comment]
We have no concept of terminal actions in the new world and definitely don't want that to be a thing. So, I take it your preference is to have the editor introduce nodes/splitting when these are edited? I think this would work, but we do have the scenario where somebody could add to that set of actions or move such a "terminal" action up.

**Comment by ericnewcomer** [comment]
Oh, I missed that bit about doing that as a minor python migration, that seems fine.

**Comment by rowanseymour** [comment]
I do remember us discussing having a 11.x migration to do that at one point - and we did it for webhook actions.. can't remember why we opted to not do the same for api actions back then.

**Comment by ericnewcomer** [comment]
..and then there is the matter of already migrated flows. The migrated flow you handed me for a repro has several of them for what it's worth. Perhaps we patch the editor in addition to that. I'll re-open this on rapidpro.
