### ISSUE TITLE
New line in variable isn't escaped in Flow var

### ISSUE THREAD

**Issue by chris-erickson** [nyaruka/goflow#805]
I think the issue here is that the `\n` in the variable is interfering with the json parsing.  I think it needs to be escaped?

<img width="718" alt="image" src="https://user-images.githubusercontent.com/3322287/69438322-6e532c00-0d0a-11ea-9bef-1da3ccc037b3.png">

```json
{
  "type": "run_result_changed",
  "created_on": "2019-11-19T18:52:57.811927162Z",
  "step_uuid": "028c8081-1a04-497a-98ac-22e3d5cc1c82",
  "name": "Mixpanel Properties",
  "value": "{\"Keyword\":\"Resist\nLoyalty>Love\"}",
  "category": ""
}

```

```json
{
  "type": "error",
  "created_on": "2019-11-19T18:52:57.812419839Z",
  "step_uuid": "f26ba3ca-3cd2-4cf1-8c5e-e024e7350b10",
  "text": "error evaluating @(json(object(\n  \"user_id\", contact.uuid,\n  \"event_name\", parent.results.mixpanel_event.value,\n  \"custom_properties\", parse_json(parent.results.mixpanel_properties.value)\n))): error calling JSON: error calling OBJECT: error calling PARSE_JSON: invalid JSON",
  "fatal": false
}
```

**Comment by chris-erickson** [comment]
FWIW, I think this user had the following as a signature or whatever in their SMS.

```
<the actual message I'm sending>
Resist
Loyalty>Love
```

**Comment by rowanseymour** [comment]
Yeah I'm pretty sure your diagnosis is correct - you can have a newline character in a result value.. but that needs to be escaped if you're constructing JSON from it. Where/how is this result being created? Need to make sure that part is creating valid JSON.

**Comment by chris-erickson** [comment]
Aha, so I suspect it's that we're building this manually.  It's the way we encode a blob of data to pass on to another flow..

<img width="657" alt="image" src="https://user-images.githubusercontent.com/3322287/69442708-ab232100-0d12-11ea-86ba-2b6815aaa186.png">

This isn't the same case exactly as above, but I think the issue is clear.

Now, strategies for making sure that json is valid?  These parameters are often user-provided so would be best if we could somehow build the object and json encode it natively.  I can't recall exactly why we did this, but I think it was to establish a contract across flows that made for more consistent behavior.  In this case, we have a "metrics" flow that expects a couple parameters to be set in advance and then delivers a metrics payload to a metrics backend.

**Comment by rowanseymour** [comment]
@chris-erickson exactly - `@(json(object(...)))` should always give you valid JSON

**Comment by chris-erickson** [comment]
Thanks for talking through it with me 😃 - was thinking we stumbled upon a bug until explaining the problem to you.  Figures.

**Comment by rowanseymour** [comment]
@chris-erickson a bug in goflow???? We write bug-free code here 😬
