### ISSUE TITLE
Include parent result references in flow inspection

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#822]
These can be used to determine which results need to be set when adding a `enter_flow` on the parent flow. Maybe something like...

```json
{
  "templates": [
    "Hi @contact"
  ],
  "dependencies": {
    "fields": [
      {"key": "gender", "name": "Gender"}
    ]
   },
  "results": [
    {
      "key": "response_1",
      "name": "Response 1",
      "categories": ["Yes", "No"],
      "node_uuids": ["72a1f5df-49f9-45df-94c9-d86f7ea064e5"]
    }
  ],
  "result_refs": {
    "parent": [
       "age",
       "response_1"
    ]
  }
}
```

Trying to think of a reason it would be useful to capture `@child.results.*` references too...

**Comment by nicpottier** [comment]
I would probably vote to just have `parent_refs` without anything under it but I suppose I could be convinced to just do both even though I don't think `child` is really useful for anything. (since we can't know for sure what child it is)

**Comment by rowanseymour** [comment]
Yeah I'm fine with that.. I'm coming up blank on reasons to include child refs..

**Comment by ericnewcomer** [comment]
Same. Parent is the only one that makes any sense to me. This is neat though!
