### ISSUE TITLE
ContactQL queries should stringify like user queries

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#834]
Currently a boolean operation stringifies like: `AND(age < 10, gender=M)` instead of `age < 10 AND gender = "M"`

We need to get these stringified for users, I could write my own function to take a contactql query and stringify it, but any objection to just me changing the goflow versions of `String` contactql nodes to stringify in a user standard way?

**Comment by rowanseymour** [comment]
Yeah I can't think why we'd ever need it the other way. Should match the `as_text` methods in the Python code which we use for normalizing search queries.
