### ISSUE TITLE
Can't fetch webhook responses of type application/geo+json

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#837]
We only fetch bodies which have an explicit content type from an accepted list, or if there's no content-type header, we use a library to try and sniff it. Can't currently make requests to https://api.weather.gov/ because `application/geo+json` isn't in our list.

We could..

1. Keeping adding types to the list as we find them
2. Sniff any response even we don't recognize the content-type
3. Download all bodies and try to parse as JSON

**Comment by nicpottier** [comment]
I think I like 3) the most just because people are terrible about setting these headers correctly. (IE, can totally see people just putting up a JSON file somewhere with nothing backing it but a web server and content-type just being text/html in that case)

**Comment by nicpottier** [comment]
And in cases where it isn't JSON, do we log why we ignore the response anywhere visible to the user?

**Comment by rowanseymour** [comment]
We have `body_ignored = true|false` on the event tho it's not saved to the `WebhookResult` and not surfaced in the contact history UI currently

**Comment by rowanseymour** [comment]
Option 1. would suck because apparently there's `application/geo+json`, `application/geojson` and `application/vnd.geo+json`

Both options 2 and 3 allow us to completely ignore the user set headers. In the case of 2 we'd be sniffing the first 512 bytes and accepting any MIME type ending `/json` or `+json`. The logic of `net.http.DetectContentType` is explained at https://mimesniff.spec.whatwg.org/

So it's just a question of whether the downside of 3. fetching potentially large non-JSON responses outweighs the upside of 100% certainty we're accepting anything which is parseable as JSON..

**Comment by nicpottier** [comment]
I don't think sniffing really works for JSON though does it? I mean there aren't mime headers in a JSON file and from what I can tell from that link there isn't any effort made to figure out if the text is actually JSON is there? (I see some attempt at detecting HTML so maybe I'm missing it)

I don't think downloading up to 1M of data is a big deal.

**Comment by rowanseymour** [comment]
Yeah true seems it just treats it as `text/plain` so you'd still have to try parsing it to know. Option 3 it is.
