### ISSUE TITLE
ReevaluateDynamicGroups doesn't remove contacts from groups with errors

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#856]
Opening an issue instead of just fixing it because maybe it requires discussion, but:
  https://github.com/nyaruka/goflow/blob/master/flows/contact.go#L342

Doesn't remove the contact from groups when there are errors in the query for a dynamic group.

Feels like it should, but perhaps this is on purpose?

**Comment by rowanseymour** [comment]
Yeah I think it should - I think best to think of a group with a query error as an empty group
