### ISSUE TITLE
Goflow operator docs are awkward

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#869]
Maybe we can add a special tag to show the actual operator (`>=`) instead of the name version `greaterthanorequal`?

![Screen Shot 2020-02-19 at 9 19 23 AM](https://user-images.githubusercontent.com/168067/74857793-10c67f80-52f9-11ea-9f10-1b341f18f975.png)

**Comment by rowanseymour** [comment]
Fixed in ce99c42a65fdae480418e4510c63782457c4d1d9

<img width="825" alt="Captura de Pantalla 2020-02-19 a la(s) 15 10 19" src="https://user-images.githubusercontent.com/675558/74871752-fe186e80-5329-11ea-8839-58aab5ae2a2d.png">
