### ISSUE TITLE
html encoding/decoding

### ISSUE THREAD

**Issue by tybritten** [nyaruka/goflow#893]
Sometimes we hit a webhook or form and the response is html encoded `Split&nbsp;Word` and we want to decode it. Also it would be handy to have an encoder for certain web forms.
creating `html_decode` and `html_encode` functions using `html.UnescapeString()` and `html.EscapeString()` seems pretty simple. 
I know you're not taking PRs on this repo but i'm willing to do the work for it.

**Comment by nicpottier** [comment]
Ya, that's an easy add for us. Not sure I see the use case for encoding (apart from just the symmetry there) but adding an `html_decode` is easy enough. We'll add it.

**Comment by tybritten** [comment]
Awesome. Not to be pushy, but any idea how long before you'll get to it?
We need the decoding for a tool to locate blood centers for people.

**Comment by tybritten** [comment]
Awesome, thanks
