### ISSUE TITLE
Rename blocked/stopped modifiers and events

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#905]
Before RapidPro and mailroom start using these we should rename to reflect upcoming changes in RP because it will be a lot harder to change things afterwards.

These are currently..

* BlockedModifier(state=true|false)
  => ContactBlockedEvent
  => ContactUnblockedEvent
* StoppedModifier(state=true|false)
  => ContactStoppedEvent
  => ContactUnstoppedEvent

But I think should be.. 

* PauseModifier(reason="blocked"|"stopped")
  => ContactBlockedEvent
  => ContactStoppedEvent 
* ResumeModifier()
  => ContactUnblockedEvent
  => ContactUnstoppedEvent

i.e. this enforces that there is one paused state with different mutually exclusive reasons

**Comment by norkans7** [comment]
I think `ContactUnblockedEvent` and `ContactUnblockedEvent` are now the same since the will be setting the `pause_type` to `null` so can we rename that to `ContactClearPauseEvent` ?

**Comment by nicpottier** [comment]
I agree Pause/Resume modifiers feel more right. Why wouldn't the events mirror those?

**Comment by norkans7** [comment]
Right I think we can have `PauseModifier(state="blocked"|"stopped")` with events 
`ContactPausedEvent` with a `pause_type` field

**Comment by norkans7** [comment]
So we'll have 

- PauseModifier(pause_type="blocked"|"stopped")
   => ContactPausedEvent
         -> pause_type field
-  ResumeModifier()
    => ContactClearPauseEvent

**Comment by rowanseymour** [comment]
We can do that.. I was thinking they might have to contain the previous state to let us handle them correctly, e.g. you might need to know what state you're resuming from to know if you do something with groups.

But on reflection I think Unstopping and Unblocking (and Unticketing?) are all just going to update `pause_type` and `paused_on` - because group membership will be handled separately by groups_changed events.

@norkans7 why not `ContactResumedEvent` instead of `ContactClearPauseEvent` ?

**Comment by norkans7** [comment]
Okay `ContactResumedEvent` works too just one event type there

thought I am wondering why that cannot be the `ContactPausedEvent` with null `pause_type`?

for the previous state I think we only reevaluate groups if the the pause_type is null, and we remove from all groups if we have pause_type `"blocked"|"stopped"`

**Comment by rowanseymour** [comment]
Can we stop and think about how this looks in expressions/context? Events are typically a reflection of state changes to the contact as represented in the context.

Are we going to have?

```
@contact.pause_type
```

I don't love that...

**Comment by rowanseymour** [comment]
or is it just `@contact.paused` (`true`|`false`) ?

**Comment by norkans7** [comment]
I think `@contact.has_ticket()` is the only that could be in the context, I  do not think we have blocked and stopped contacts start in flows

**Comment by rowanseymour** [comment]
We've talked about allowing users to block and stop contacts via actions so I would have thought it's reasonable to see that state in expressions.. unless those are terminal actions

**Comment by nicpottier** [comment]
`@contact.status` sounds nicer to me for sure. (one of `active`, `paused`, `blocked`, `stopped`)

**Comment by rowanseymour** [comment]
I like that.. would suggest then the modifier and event are just...

* StatusModifier(status="active"|"paused"|"blocked"|"stopped")
    => ContactStatusChangedEvent

Which feels a lot more like existing modifiers/events

**Comment by rowanseymour** [comment]
That would match what we have for runs: `@run.status` one of `active`, `completed`, ...

**Comment by nicpottier** [comment]
Ya this all sounds right to me.

**Comment by rowanseymour** [comment]
Fixed in https://github.com/nyaruka/goflow/pull/906
