### ISSUE TITLE
Step limit exceed or run child for flow error

### ISSUE THREAD

**Issue by matmsa27** [nyaruka/goflow#933]
Hi everyone, there is a possibility to change the number of steps ([maxStepsPerSprint](https://github.com/nyaruka/goflow/blob/master/flows/engine/engine.go#L60
)) to avoid loops from 100 to 200 for example? 

We have customers treating COVID, and in some flows, they execute a lot of steps on flows, more than 100, and they get errors about step limited.

**Comment by rowanseymour** [comment]
This is already a setting in mailroom: https://github.com/nyaruka/mailroom/blob/ecd2a102793a43e7d11f92afd9e7d4e1a93d3a29/config/config.go#L41

**Comment by matmsa27** [comment]
Hi @rowanseymour, thanks a lot for your fast reply and your attention.
