### ISSUE TITLE
Excellent should always cast to decimal for equality, comparison

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#95]
`>`, `<`, `<=`, `>=`, `=` and `!=` should always cast arguments to decimal (and error if not possible to). Ambiguity with string is confusing and unpredictable.

**Comment by nicpottier** [comment]
We could implement a decimal version for time.Time as being epoch (in seconds) to still allow easy time comparisons.

**Comment by nicpottier** [comment]
@rowanseymour how do we feel about this? Still feels right to me.. can add a `CMP_STRING` function for the string case?

**Comment by rowanseymour** [comment]
@nicpottier yeah I really like the idea that those operators are always numeric
