### ISSUE TITLE
Allow urn != "x" and tel != "x" in queries

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#950]
Just noticed goflow parsing doesn't disallow this, but mailroom only allows `urn != ""` and `tel != ""`. Not completely sure what's doable in ES here.

**Comment by nicpottier** [comment]
I think these are possible without any problems on the ES side though we may need to experiment to make sure that's actually the case.

**Comment by rowanseymour** [comment]
Working on that now - would be nice to say `=` and `!=` are supported for everything
