### ISSUE TITLE
Add `(empty body)` or ` ` to email body when empty?

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#955]
Mailgun fails in sending emails that have empty bodies. The editor doesn't allow empty bodies, but it is pretty easy to create one by referring to variables that don't exist.

Perhaps we should substitute empty with a space so that the email actually sends? Or some other placeholder?

**Comment by rowanseymour** [comment]
Space sounds reasonable - tho I should probably check that that is enough to get by mailgun and it doesn't trim it

**Comment by rowanseymour** [comment]
Sounds like empty emails might get someone flagged as spam - see https://github.com/mailgun/mailgun-php/issues/290

Which makes me lean toward something like `(empty body)` - if people don't like it they should put something in their emails!

**Comment by nicpottier** [comment]
Or `this space intentionally left blank` :)

**Comment by rowanseymour** [comment]
Added `(empty body)` in #965
