### ISSUE TITLE
Retry email sending?

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#956]
Servers occasionally have connectivity issues, maybe we should retry emails a few times if they fail with a timeout between them. Essentially something similar to what we do with webhooks.

**Comment by rowanseymour** [comment]
I've noticed the `go-mail` package actually does 1 retry with no timeout.. I think we'd disable that if we added our own retry stuff

**Comment by rowanseymour** [comment]
Looked into this a bit - the challenge is knowing whether an err we get back from `DialAndSend` is retry-able. Our current SMTP library doesn't easily support that, and isn't the most maintained project right now so did start looking at whether it would be worth switching to https://github.com/jordan-wright/email and https://github.com/knadh/smtppool. We don't really need pooling but the latter library adds support for retrying.

**Comment by nicpottier** [comment]
Just a quick note here that we saw this again, this time gmail SMTP server timing out and a customer was annoyed about it. So having some kind of retry on email sends may be worth looking into again.
