### ISSUE TITLE
MsgTemplating without country reference

### ISSUE THREAD

**Issue by koallann** [nyaruka/goflow#961]
Hey guys, I noted that the country field from `TemplateTranslation` isn't being marshaled into message metadata, making [this adjustment](https://github.com/nyaruka/rapidpro/pull/2836) (and others) not to take effect.

I arrived at the [MsgTemplating](https://github.com/nyaruka/goflow/blob/master/flows/msg.go#L151) as the cause of the lack of this parameter, that's, that struct doesn't have the country field.

**Comment by rowanseymour** [comment]
Am bit confused. We have templates in the DB with `language=por, country=BR`, those become assets, we pick a translation, we save a templating object on the MsgOut (at this point we lose country so it's just `language=por`).. Mailroom saves that into the `msgs_msg` metadata... but don't we need to send a code like `pt_BR` to whatsapp? I can't find the code that would convert the 3 char language code to a 2 char language code...

**Comment by nicpottier** [comment]
The translation is done here:
  https://github.com/nyaruka/courier/blob/master/handlers/whatsapp/whatsapp.go#L824

But ya, does seem we should just pass through the country in MsgTemplating.

**Comment by rowanseymour** [comment]
Added in https://github.com/nyaruka/goflow/pull/967

**Comment by koallann** [comment]
Just to be clearer, we'd no problems in mapping `language` and `country` to the WhatsApp code because there's a default code for each language in the Courier, for example: `por` -> `pt_PT`.
