### ISSUE TITLE
HasNumber rule should include Arabic numerals

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#969]
We've heard from various users that sometimes contacts reply to numerical questions with numbers in other numeral systems. The most common being Eastern Arabic numerals ٠١٢٣٤٥٦٧٨٩

The result of the test would still be a regular XNumber so..

```
has_number("hi")  => false, ""
has_number("12")  => true, 12
has_number("ج")  => false, ""
has_number("١٢")  => true, 12
has_number("٠.٥")  => true, 0.5
```

And could be implemented using a simple mapping of digit characters applied before parsing, e.g. `١` => `1`

**Comment by nicpottier** [comment]
Any interesting rules around either decimals or the "thousands separator" we need to deal with? (we don't really deal with the latter already so I guess not so much of a concern)

If it is just doing a regex then ya, seems straightforward.

**Comment by rowanseymour** [comment]
According to my Palestinian Arabic teacher friend, they use , . same as we do - however that's already configurable and passed in via the environment, so if there's a country out there using Arabic numerals and some other thousands or decimal separator, we're good to go!
