### ISSUE TITLE
Phone number detection picks up phone numbers inside URLs

### ISSUE THREAD

**Issue by putorti** [nyaruka/goflow#979]
https://time.com/5912705/covid-19-stop-spread-christmas/

This particular link will trigger the split "has a phone number" — I think probably we can all agree it's not in this case. Probably should add the exception to it being inside a URL.

**Comment by putorti** [comment]
The "result" of a split on my variable containing that URL gives me this:

<img width="177" alt="image" src="https://user-images.githubusercontent.com/82857/101053556-eb3bf700-3555-11eb-8549-397ccdd055d8.png">

Which, isn't a valid phone number either, I don't think you can use a +1 and then not have an area code?

**Comment by rowanseymour** [comment]
I _think_ it's ok for `has_phone` to find a phone numbers in URLs.. https://phones.com?num=12065912705 has a phone number. The problem in your example is that 5912705 is only a number in a local context. It seems we've been leaning on a function in the phonenumbers library which includes local numbers, so have made a fix for gocommon at https://github.com/nyaruka/gocommon/pull/40

**Comment by rowanseymour** [comment]
Fixed in b5a89e19c92ae2088f4fd80bdb08793f7cf6c058
