### ISSUE TITLE
Flow inspection should include information about waits and sends

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#980]
In RapidPro we want to give users options to start flows that don't interrupt other flows. This definitely means that the flow can't lead to a wait, tho could possibly allow sending of messages. Probably best not to allow subflows so we don't have to recursively check each subflow destination.

Maybe the most flexible approach at the engine level would be just list out features that the flow uses. That way the caller (in this case RapidPro) can determine for itself what it wants to allow with a given flow without having understand the flow spec, e.g. include this in flow inspection:

```
"features": ["waits", "sends", "webhooks", "subflows", "email"],
"issues": [...],
"dependencies": [...]
```

And that information may be useful elsewhere, e.g. determining whether a flow can be started without an org having a channel.

**Comment by nicpottier** [comment]
I like this. Any reason for this not to be exactly the union if actions + waits?

**Comment by rowanseymour** [comment]
I went back and forth on that.. and figured maybe that was asking the caller to know too much about the flow spec - i.e. RapidPro has to know that sending is both `send_broadcast` and `send_msg`, subflows are both `enter_flow` and `start_session`.. but I could be persuaded that is fine.

**Comment by rowanseymour** [comment]
Have persuaded myself it's most flexible to keep this as high-level flags so it can include anything.. maybe `looping` is a feature

**Comment by rowanseymour** [comment]
See PR for why we created a new flow type instead..
