### ISSUE TITLE
Docs shouldn't be in the repo?

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#994]
It's getting pretty annoying that any PR which changes context or expression functions generates a diff with changes to 50 html files. Generated doc files also tend to differ slightly depending on who is making the PR since they depend on local versions of gettext and pandoc executables.

We already host the latest version of the docs at https://textit.com/mr/docs/ and https://app.rapidpro.com/mr/docs/ so don't need https://nyaruka.github.io/goflow/en-us/

Would mean that the mailroom release process generates the docs that it bundles itself with.

**Comment by rowanseymour** [comment]
Have disabled github pages that was exposing /docs and updated the README to point to https://textit.com/mr/docs/

**Comment by rowanseymour** [comment]
Seems a bit awkward to have mailroom checkout build and run the docgen part of goflow - so now thinking goflow will use github actions to create a very simple release which is just the code + a zip of the docs. Then mailroom just needs to grab that asset from the release.

**Comment by nicpottier** [comment]
Is it that bad? Feels like an extra layer of indirection/failure for us depending on a goflow release being "built" before mailroom can build it.

**Comment by rowanseymour** [comment]
I don't think there's a big issue there.. you shouldn't be building a new mailroom release off a goflow tag that hasn't passed CI anyway. And the goflow docs feels like something that belongs in goflow..

**Comment by rowanseymour** [comment]
Docs gone - unit test still checks we can build them tho
